<?php $this->headScript()->appendFile('/js/jquery.are-you-sure.js')
                         ->appendFile('/js/project/task/add.js'); ?>

<div class="row">
    
    <div class="col-md-12 title">
        <h1>Create new task</h1>
        <hr>
      
    </div>
    
    <div class="col-md-12">
        <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('project/default', array(
                'controller' => 'task',
                'action' => 'add',
                'id' => $this->milestoneId)));
            $form->prepare();

            echo $this->form($form);
        ?>
        
    </div>
</div>

