<div class="row">
    <div class="col-md-12 title">
        <h1>Task Details</h1>
        <hr>
        
        <i class="fa fa-cubes fa-3x pull-left"></i>
        <h4><?php echo $this->task->getName(); ?></h4>
        <p>
            <a href="<?php echo $this->url('project/default', array('controller' => 'task', 'action' => 'edit', 'id' => $this->task->getId())); ?>"><i class="fa fa-edit"></i></a>
            <a href="<?php echo $this->url('project/default', array('controller' => 'task', 'action' => 'delete', 'id' => $this->task->getId())); ?>"><i class="fa fa-remove"></i></a>
        </p>
        
        <!-- Task description -->
        <p><?php echo $this->task->getDescription();?></p>
        
        <div>
            
            <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist" id="tabs">
                <li role="presentation" class="active"><a href="#detail" aria-controls="home" role="tab" data-toggle="tab">Detail</a></li>
                <li role="presentation"><a href="#history" aria-controls="history" role="tab" data-toggle="tab">History</a></li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content">

                <!-- Task details tab -->
                <div role="tabpanel" class="tab-pane active" id="detail">
                    <div class="row">
                        <div class="col-lg-6">
                                <table class="table table-condensed table-bordered">
                                    <tbody>
                                         <tr>
                                            <th style="width: 35%;">Name</th>
                                            <td><?php echo $this->task->getName(); ?></td>
                                        </tr>
                                        <tr>
                                            <th>Scheduled Start Time</th>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <th>Estimated Hours</th>
                                            <td><?php echo $this->task->getEstimatedHours(); ?></td>
                                        </tr>
                                        <tr>
                                            <th>Estimated Cost</th>
                                            <td><?php echo $this->task->getActualHours(); ?></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>

                    </div>
                </div>

                <!-- History tab -->
                <div role="tabpanel" class="tab-pane" id="history">
                    <div class="row">
                        <div class="col-lg-12">
                            <p>There is no history to display yet.</p>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        
        <br>

        <p>
        <span class="text-primary">Comments</span>
        <a class="btn btn-primary btn-xs pull-right" href="<?php echo $this->url('project/default', array(
            'controller' => 'task',
            'action' => 'comment',
            'id' => $this->task->getId()
        )) ?>">Add Comment</a>
        </p>
        <?php foreach($this->task->getComments() as $comment):?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <b>Guest </b><small class="text-muted"><?php echo $comment->getCreatedTime()->format(DATE_COOKIE); ?></small>
                <span class="pull-right">
                    <a href="<?php echo $this->url('project/default', array('controller' => 'comment', 'action' => 'edit', 'id' => $comment->getId())); ?>"><i class="fa fa-edit"></i></a>
                    <a href="<?php echo $this->url('project/default', array('controller' => 'comment', 'action' => 'delete', 'id' => $comment->getId())); ?>"><i class="fa fa-remove"></i></a>
                </span>
            </div>
            <div class="panel-body">
                <p><?php echo $comment->getComment();?></p>
            </div>        
        </div>
        <?php endforeach;?>
        
    </div>
</div>