<?php
    $this->headLink()->appendStylesheet('/css/datatables.css');
    $this->headScript()->appendFile('/js/datatables.js')
                       ->appendFile('/js/project/task/index.js');
?>

    <!-- Breadcrumb -->
    <ul class="breadcrumb">
        <li><a href="<?php echo $this->url('cobalt');?>"><i class="fa fa-home"></i> Home</a></li>
        <li><i class="fa fa-angle-right"></i> Tasks</li>
    </ul>

    <div class="row">
        <div class="col-md-12">

            <h1 class="title">Tasks</h1>
            <a class="btn btn-action pull-right" href="<?php echo $this->url('project/default', array(
                'controller' => 'task', 'action' => 'add')); ?>">Create New Task</a>
            <hr>

            <table id="tasks" class="table">
                <thead>
                    <tr>
                        <th>Task</th>
                        <th>Status</th>
                        <th>Priority</th>
                        <th>Estimated Hours</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->tasks as $task): ?>
                    <tr>
                        <td><a href="<?php echo $this->url('project/default', array('controller' => 'project', 'action' => 'detail', 'id'         => $task->getId())); ?>">
                            <?php echo $task->getName(); ?>
                        </a></td>
                        <td><?php echo $task->getStatus()->getName(); ?></td>
                        <td><?php echo $task->getPriority()->getName(); ?></td>
                        <td><?php echo $task->getEstimatedHours(); ?></td>
                        <td>
                            <a class="btn btn-warning btn-sm" href="<?php echo $this->url('project/default', array('controller' => 'project', 'action' => 'edit', 'id' => $task->getId()));?>">Edit</a>
                            <a class="btn btn-danger btn-sm" href="<?php echo $this->url('project/default', array('controller' => 'project', 'action' => 'delete', 'id' => $task->getId()));?>">Delete</a>
                        </td>
                    </tr>
                    <?php endforeach; ?>

                </tbody>

            </table>
        </div>
    </div>