<?php
    $this->headLink()->appendStylesheet('/css/dataTables.bootstrap.css');
    $this->headScript()->appendFile('/js/jquery.dataTables.js')
                       ->appendFile('/js/dataTables.bootstrap.js')
                       ->appendFile('/js/notification/index/index.js');
?>
        
    <div class="row">
        <div class="col col-md-12 title">
            <h1>Notifications</h1>
            <hr>
        </div>
        <div class="col-md-12">
            <table id="tickets" class="table table-bordered table-condensed table-cobalt" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th></th>
                        <th>Notification</th>
                        <th></th>
                        
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->notifications as $notification): ?> 
                    <tr>
                        <td></td>
                        <td><?php echo $notification->getDescription(); ?></td>
                        <td><a href="<?php echo $this->url('template'); ?>">Edit Template</a></td>
                    </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>