<?php
    $this->headScript()->appendFile('https://cdn.tinymce.com/4/tinymce.min.js')
                       ->appendFile('/js/application/index/template.js');
?>

    <div class="row">
        <div class="col-md-12 title">
            <h1>Edit Notification Template</h1>
            <hr>
        </div>
        <div class="col-md-9">
            <?php
                $form = $this->form;
                $form->setAttribute('action', $this->url('template', array('id' => $this->notification->getId())));
                $form->prepare();
                echo $this->form()->openTag($form);
                echo $this->form($form);
                echo $this->form()->closeTag();
            ?>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label for="sel1">Select list:</label>
                <select class="form-control" id="sel1" multiple="multiple" size="10">
                    <?php foreach ($this->fields as $descr => $field): ?>
                    <option value="<?php echo $field; ?>"><?php echo $descr; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
    </div>