<div class="row">
    <div class="col-md-12 title">
        <h1>Delete Support Ticket</h1>
        <hr>
        <p>Are you sure you want to delete ticket number <?php echo sprintf('%08d', $this->ticket->getId()); ?>?</p>
        
        <form action="<?php echo $this->url('cobalt/default', array(
            'controller' => 'ticket',
            'action' => 'delete',
            'id' => $this->ticket->getId()
        )); ?>" method="post">
            <div>
                <input class="btn btn-primary" type="submit" name="del" value="Yes" />
                <input class="btn btn-default" type="submit" name="del" value="No" />
            </div>
        </form>
    </div>
</div>

