<?php
    $this->headScript()->appendFile('/js/tinymce/tinymce.min.js')
                       ->appendFile('/js/tinymce/plugins/textcolor/plugin.min.js')
                       ->appendFile('/js/jquery.are-you-sure.js')
                       ->appendFile('/js/cobalt/ticket/edit.js');
?>
    <div class="row">
        <div class="col-md-12 title">
            <h1>Update Support Ticket</h1>
            <hr>
        </div>
        <div class="col-md-12">
            <?php
                $form = $this->form;
                $form->setAttribute('action', $this->url('cobalt/default', array(
                    'controller' => 'ticket',
                    'action'     => 'edit',
                    'id'         => $this->id)));
                $form->get('submit')->setLabel('Edit');
                $form->prepare();
                echo $this->form()->openTag($form);
                echo $this->form($form);
                echo $this->form()->closeTag();
            ?>
        </div>
    </div>