<?php
    $this->headLink()->appendStylesheet('/css/dataTables.bootstrap.css');
    $this->headScript()->appendFile('/js/jquery.dataTables.js')
                       ->appendFile('/js/dataTables.bootstrap.js')
                       ->appendFile('/js/cobalt/ticket/index.js');
?>
        
    <div class="row">
        <div class="col col-md-12 title">
            <h1>Support Tickets</h1>
            <a class="btn btn-primary btn-sm pull-right" href="<?php echo $this->url('cobalt/default', array('controller' => 'ticket', 'action' => 'add'));?>">New Ticket</a>
            <hr>
        </div>
        <div class="col-md-12">
            <table id="tickets" class="table table-bordered table-condensed table-cobalt" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th></th>
                        <th>Ticket No</th>
                        <th>Status</th>
                        <th>Subject</th>
                        <th>Priority</th>
                        <th>Requester</th>
                        
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->tickets as $ticket): ?> 
                    <tr>
                        <th style="width: 1%;" nowrap>
                            <i><a href="<?php echo $this->url('cobalt/default', array('controller' => 'ticket', 'action' => 'edit', 'id' => $ticket->getId()));?>"><i class="fa fa-edit"></i></a>
                                <a href="<?php echo $this->url('cobalt/default', array('controller' => 'ticket', 'action' => 'delete', 'id' => $ticket->getId()));?>"><i class="fa fa-remove"></i></a>
                        </th>
                        <td><a href="<?php echo $this->url('cobalt/default', array('controller' => 'ticket', 'action' => 'detail', 'id' => $ticket->getId()));?>">
                            <?php echo sprintf('%08d', $ticket->getId());?></a></td>
                        <td><?php echo $ticket->getStatus()->getName(); ?></td>
                        <td><?php echo $ticket->getSubject(); ?></td>
                        <td>
                            <?php
                                $priorityClass="label label-default";
                                if ($ticket->getPriority()->getName() == 'High') {
                                    $priorityClass="label label-danger";
                                }
                                if ($ticket->getPriority()->getName() == 'Medium') {
                                    $priorityClass="label label-warning";
                                }
                            ?>
                            <span class="<?php echo $priorityClass;?>"><?php echo $ticket->getPriority()->getName(); ?></span>
                        </td>
                        <td><?php echo $ticket->getRequestor()->getDisplayName(); ?></td>
                    </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>