<?php $this->headScript()->appendFile('/js/jquery.are-you-sure.js')
                         ->appendFile('/js/cobalt/software-category/add.js'); ?>
    <div class="row">
        <div class="col-md-12 title">
            <h1>Add New Software Category</h1>
            <hr>
        </div>
        <div class="col-md-6">
            <?php
                $form = $this->form;
                $form->setAttribute('action', $this->url('cobalt/default', array('controller' => 'softwarecategory', 'action' => 'add')));
                $form->prepare();
                echo $this->form()->openTag($form);
                echo $this->form($form);
                echo $this->form()->closeTag();
            ?>
        </div>
    </div>