<div class="row">
    <div class="col-md-12 title">
        <h1>Delete Software License</h1>
        <hr>
        <p>Are you sure you want to delete the software license <i>'<?php echo $this->license->getLicenseKey(); ?>'</i> ?</p>
        
        <form action="<?php echo $this->url('cobalt/default', array(
            'controller' => 'softwarelicense',
            'action' => 'delete',
            'id' => $this->license->getId()
        )); ?>" method="post">
            <div>
                <input class="btn btn-primary" type="submit" name="del" value="Yes" />
                <input class="btn btn-default" type="submit" name="del" value="No" />
            </div>
        </form>
    </div>
</div>