<div class="row">
    <div class="col-md-12 title">
        <h1>Delete Hardware</h1>
        <hr>
    </div>
    <div class="col-md-12">
        <p>Are you sure you want to delete the hardware <i>'<?php echo $this->hardware->getReference(); ?>'</i> ?</p>    
        <form action="<?php echo $this->url('cobalt/default', array(
            'controller' => 'hardware',
            'action' => 'delete',
            'id' => $this->hardware->getId()
        )); ?>" method="post">
            <div>
                <input class="btn btn-primary" type="submit" name="del" value="Yes" />
                <input class="btn btn-default" type="submit" name="del" value="No" />
            </div>
        </form>
    </div>
</div>