<?php
    $this->headLink()->appendStylesheet('/css/datatables.css');
    $this->headScript()->appendFile('/js/datatables.js')
                       ->appendFile('/js/bootstrap/tab.js')
                       ->appendFile('/js/jquery-plugin/stickytabs.js')
                       ->appendFile('/js/cobalt/hardware/detail.js');
?>

<div class="row">
    <div class="col-md-12 title">
            
        <h1>Hardware Details</h1>
        <hr>
            
        <i class="fa fa-building fa-3x pull-left"></i>
        <h4><?php echo $this->hardware->getReference(); ?></h4>
        <p>
            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'hardware', 'action' => 'edit', 'id' => $this->hardware->getId())); ?>"><i class="fa fa-edit"></i></a>
            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'hardware', 'action' => 'delete', 'id' => $this->hardware->getId())); ?>"><i class="fa fa-remove"></i></a>
        </p>
        
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist" id="tabs">
            <li role="presentation" class="active"><a href="#details" aria-controls="home"             role="tab" data-toggle="tab">Details</a></li>
            <li role="presentation"><a href="#network-adapters"       aria-controls="network-adapters" role="tab" data-toggle="tab">Network Adapters</a></li>
            <li role="presentation"><a href="#monitoring"             aria-controls="monitoring"       role="tab" data-toggle="tab">Monitoring</a></li>
            <li role="presentation"><a href="#history"                aria-controls="history"          role="tab" data-toggle="tab">History</a></li>
        </ul>
        
        <!-- Tab panes -->
        <div class="tab-content">
            
            <!-- Details tab -->
            <div role="tabpanel" class="tab-pane active" id="details">
                <div class="row">
                    <div class="col-lg-6">
                        <table class="table table-condensed table-bordered">
                            <tbody>
                                <tr>
                                    <th style="width: 35%;">Unique Reference</th>
                                    <td><?php echo $this->hardware->getReference(); ?></td>
                                </tr>
                                <tr>
                                    <th>Type</th>
                                    <td><?php echo $this->hardware->getType()->getName(); ?></td>
                                </tr>
                                <tr>
                                    <th>Status</th>
                                    <td>
                                        <div class="status" style="border-left-color: <?php echo $this->hardware->getStatus()->getColor();?>">
                                            <?php echo $this->hardware->getStatus()->getName(); ?>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <th>Model</th>
                                    <td><?php echo $this->hardware->getModel(); ?></td>
                                </tr>
                                <tr>
                                    <th>Serial Number</th>
                                    <td><?php echo $this->hardware->getSerialNumber(); ?></td>
                                </tr>
                                <tr>
                                    <th>Manufacturer</th>
                                    <td><?php echo $this->hardware->getManufacturer()->getName(); ?></td>
                                </tr>
                                <tr>
                                    <th>Asset Number</th>
                                    <td><?php echo nl2br($this->hardware->getAssetNumber()); ?></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div id="imgdrop" class="col-lg-6">
                        
                        <?php if ( $hardware->getImage()) :?>
                        <img id="img" width="320" src="<?php echo '/cobalt/computer/' . $hardware->getImage();?> ">
                        <?php else : ?>
                        <div id="img">
                            <div class="text-center"><i class="fa fa-5x fa-download"></i></div>
                            <div class="text-center">Drop image here</div>
                        </div>
                        <?php endif;?>
                        </form>
                    </div>
                </div>
            </div>
            
            <!-- Network Adapters tab -->
            <div role="tabpanel" class="tab-pane" id="network-adapters">
                <table class="table table-condensed table-bordered">
                <tbody>
                    <tr>
                        <th></th>
                        <th>Name</th>
                        <th>Physical Address</th>
                        <th>DHCP Enabled</th>
                        <th>IPv4 Address</th>
                        <th>Default Gateway</th>
                    </tr>
                    <?php foreach($hardware->getNetworkAdapters() as $adapter){
                        echo $this->partial('partial/network-adapter', array('adapter' => $adapter));
                    } ?>
                    </tbody>
                </table>
                <a class="btn btn-success btn-sm" href="<?php echo $this->url('cobalt/default', array(
                    'controller' => 'NetworkAdapter',
                    'action'     => 'add',
                    'id'         => $this->hardware->getId()
                        ));?>">Add Adapter</a>
            </div>
            
            <!-- Monitoring tab -->
            <div role="tabpanel" class="tab-pane" id="monitoring">
                <table class="table table-condensed table-bordered">
                <tbody>
                    <tr>
                        <th></th>
                        <th>Adapter Name</th>
                        <th>IPv4 Address</th>
                    </tr>
                    <?php foreach($hardware->getNetworkAdapters() as $adapter): ?> 
                        <tr>
                            <td class="text-center" width="32">
                            <?php if ($adapter->getMonitor()): ?>
                                <input type="checkbox" name="<?php echo $adapter->getId();?>" value="<?php echo $adapter->getId();?>" checked>
                            <?php else: ?>
                                <input type="checkbox" name="<?php echo $adapter->getId();?>" value="<?php echo $adapter->getId();?>">
                            <?php endif; ?>
                            </td>
                            <td><?php echo $adapter->getName();?></td>
                            <td><?php echo $adapter->getIpv4Address();?></td>
                        </tr>
                    <?php endforeach ?>
                    </tbody>
                </table>
            </div>
            
            <!-- History tab -->
            <div role="tabpanel" class="tab-pane" id="history">
                <?php echo $this->partial('application/partial/history_table.phtml', array('history' => $this->history));?>
            </div>
            
        </div>
        
    </div>
    
</div>

