<?php
    $this->headLink()->appendStylesheet('/css/dataTables.bootstrap.css');
    $this->headScript()->appendFile('/js/jquery.dataTables.js')
                       ->appendFile('/js/dataTables.bootstrap.js')
                       ->appendFile('/js/cobalt/hardware/index.js');
?>
        
    <div class="row">
        <div class="col col-md-12 title">
            <h1>Hardware</h1>
            <a class="btn btn-success btn-sm pull-right" href="<?php echo $this->url('cobalt/default', array('controller' => 'hardware', 'action' => 'add'));?>">New Hardware</a>
            <hr>
        </div>
        <div class="col-md-12">
            <table id="hardware" class="table table-bordered table-condensed table-cobalt" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th></th>
                        <th>Unique Ref</th>
                        <th>Name</th>
                        <th>Model</th>
                        <th>Serial Number</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->hardware as $hardware): ?> 
                    <tr>
                        <?php
                            $class = get_class($hardware);
                            $controller = strtolower(substr($class, strrpos($class, '\\') + 1));
                        ?>
                        <td style="width: 1%;" nowrap>
                            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'hardware', 'action' => 'edit', 'id' => $hardware->getId()));?>"><i class="fa fa-edit"></i></a>
                            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'hardware', 'action' => 'delete', 'id' => $hardware->getId()));?>"><i class="fa fa-remove"></i></a>
                        </td>
                        <td><a href="<?php echo $this->url('cobalt/default', array('controller' => $controller, 'action' => 'detail', 'id' => $hardware->getId()));?>">
                            <?php echo $hardware->getReference();?></a></td>
                        <td><?php echo $hardware->getName();?></td>
                        <td><?php echo $hardware->getModel();?></td>
                        <td><?php echo $hardware->getSerialNumber();?></td>
                    </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>