<?php
    $this->headLink()->appendStylesheet('http://cdn.jsdelivr.net/chartist.js/latest/chartist.min.css');
    $this->headScript()->appendFile('http://cdn.jsdelivr.net/chartist.js/latest/chartist.min.js')
                       ->appendFile('/js/cobalt/hardware/summary.js');
?>

<div class="row">
        <div class="col col-md-12 title">
            <h1>Hardware Summary Overview</h1>
            <hr>
        </div>
</div>

<div class="row">
    <div class="col-md-3">
        <table class="table table-bordered table-condensed table-cobalt">
            <thead>
                <tr>
                    <th>Status</th>
                    <th>Count</th>
                </tr>
            </thead>
            <?php foreach ($this->summaryByStatus as $status): ?>
            <tr>
                <td><?php echo $status['name']; ?></td>
                <td><?php echo $status[1]; ?></td>
            </tr>
            <?php endforeach; ?>
            <tbody>

            </tbody>
        </table>
    </div>
    <div class="col-md-9">
        <div class ='ct-chart'></div>
    </div>
         
</div>

<div class="row">
    <div class="col-md-3">
        <table class="table table-bordered table-condensed table-cobalt">
            <thead>
                <tr>
                    <th>Type</th>
                    <th>Count</th>
                </tr>
            </thead>
            <?php foreach ($this->summaryByType as $type): ?>
            <tr>
                <td><?php echo $type['name']; ?></td>
                <td><?php echo $type[1]; ?></td>
            </tr>
            <?php endforeach; ?>
            <tbody>

            </tbody>
        </table>
    </div>
    <div class="col-md-9">
        <div class ='ct-chart'></div>
    </div>
         
</div>

<div class="row">
    <div class="col-md-3">
        <table class="table table-bordered table-condensed table-cobalt">
            <thead>
                <tr>
                    <th>Manufacturer</th>
                    <th>Count</th>
                </tr>
            </thead>
            <?php foreach ($this->summaryByManufacturer as $manufacturer): ?>
            <tr>
                <td><a href="<?php echo $this->url('cobalt/default', array(
                    'controller' => 'hardware-manufacturer',
                    'action' => 'detail',
                    'id' => $manufacturer['id']
                ));?>">
                    <?php echo $manufacturer['name']; ?>
                </a></td>
                <td><?php echo $manufacturer[1]; ?></td>
            </tr>
            <?php endforeach; ?>
            <tbody>

            </tbody>
        </table>
    </div>
    <div class="col-md-9">
        <div class ='ct-chart'></div>
    </div>
         
</div>
