<?php
    $this->headLink()->appendStylesheet('http://cdn.jsdelivr.net/chartist.js/latest/chartist.min.css');
    $this->headScript()->appendFile('http://cdn.jsdelivr.net/chartist.js/latest/chartist.min.js')
                       ->appendFile('/js/cobalt/hardware/summary.js');
?>

    
<div class="row">
    <div class="col-md-3">
        <table class="table table-bordered table-condensed table-cobalt">
            <thead>
                <tr>
                    <th>Status</th>
                    <th>Count</th>
                </tr>
            </thead>
            <?php foreach ($this->summary as $status): ?>
            <tr>
                <td><?php echo $status['name']; ?></td>
                <td><?php echo $status[1]; ?></td>
            </tr>
            <?php endforeach; ?>
            <tbody>

            </tbody>
        </table>
    </div>
    <div class="col-md-9">
        <div class ='ct-chart'></div>
    </div>
         
</div>


