language: php
php:
  - '5.6'
  - '7.0'
install:
  - composer install
before_script:
  - echo "extension=ldap.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
script: phpunit --configuration tests/phpunit.xml
    