language: php
sudo: required
php:
  - '5.6'
  - '7.0'
services:
  - mysql
install:
  - echo "extension=ldap.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer install
  - mysql -e 'create database cobalt;'
script: phpunit --configuration tests/phpunit.xml
    