<h1>Change Password</h1>

<?php $form = $this->form; ?>

<?php echo $this->form(null, null)->openTag($form); ?>
<?php echo $this->formRow($form->get('current_password')); ?>
<?php echo $this->formRow($form->get('new_password')); ?>
<?php echo $this->formRow($form->get('confirm_password')); ?>
<?php echo $this->formRow($form->get('submit')); ?>
<?php echo $this->form()->closeTag($form); ?>

<?php if($this->message): ?>
    <br>
    <span class="alert alert-danger"><b>Error: </b><?php echo $this->message; ?></span>
<?php endif; ?>