<div class="row">
    <div class="col-md-12 title">
            
        <h1>Company Details</h1>
        <hr>
            
        <i class="fa fa-building fa-3x pull-left"></i>
        <h4><?php echo $this->company->getName(); ?></h4>
        <p>
            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'company', 'action' => 'edit', 'id' => $this->company->getId())); ?>"><i class="fa fa-edit"></i></a>
        <a href="<?php echo $this->url('cobalt/default', array('controller' => 'company', 'action' => 'delete', 'id' => $this->company->getId())); ?>"><i class="fa fa-remove"></i></a>
        </p>
        
    
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist" id="tabs">
            <li role="presentation" class="active"><a href="#details" aria-controls="home"    role="tab" data-toggle="tab">Details</a></li>
            <li role="presentation"><a href="#offices"                aria-controls="offices" role="tab" data-toggle="tab">Offices</a></li>
            <li role="presentation"><a href="#history"                aria-controls="history" role="tab" data-toggle="tab">History</a></li>
        </ul>
        
        <!-- Tab panes -->
        <div class="tab-content">

            <!-- Details tab -->
            <div role="tabpanel" class="tab-pane active" id="details">
                <div class="row">
                    <div class="col-lg-6">
                        <table class="table table-condensed table-bordered">
                            <tbody>
                                <tr>
                                    <th style="width: 35%;">Company Name</th>
                                    <td><?php echo $this->company->getName(); ?></td>
                                </tr>
                                <tr>
                                    <th>Address</th>
                                    <td><?php echo $this->company->getAddress(); ?></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>

            <!-- Offices tab -->
            <div role="tabpanel" class="tab-pane" id="offices">
                    <div class="row">
                        <div class="col-md-12">
                            <table class="table table-condensed">
                                <tr>
                                    <th></th>
                                    <th>Name</th>
                                    <th>Address</th>
                                </tr>
                                <?php foreach ($this->company->getOffices() as $office): ?>
                                <tr>
                                    <td style="width: 1%;" nowrap>
                                        <a href="<?php echo $this->url('project/default', array('controller' => 'office', 'action' => 'edit', 'id' => $office->getId()));?>">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                        <a href="<?php echo $this->url('project/default', array('controller' => 'office', 'action' => 'delete', 'id' => $office->getId()));?>">
                                            <i class="fa fa-remove"></i>
                                        </a>
                                    </td>
                                    <td><a href="<?php echo $this->url('project/default', array('controller' => 'office', 'action' => 'detail', 'id' => $office->getId()));?>">
                                        <?php echo $office->getName(); ?>
                                    </a></td>
                                    <td><?php echo $office->getName(); ?></td>
                                    <td><?php echo $office->getAddress(); ?></td>
                                </tr>
                                <?php endforeach; ?>
                            </table>
                            <a class="btn btn-default btn-sm" href="<?php echo $this->url('project/default', array(
                                'controller' => 'office',
                                'action' => 'add',
                                'id' => $this->company->getId()
                            )) ?>">Add Office</a>
                        </div>
                    </div>                    
                </div>
            
            

            <!-- History tab -->
            <div role="tabpanel" class="tab-pane" id="history">
                No history to show yet.
            </div>
        </div>
    </div>

</div>