<?php
    $this->headLink()->appendStylesheet('/css/dataTables.bootstrap.css');
    $this->headScript()->appendFile('/js/jquery.dataTables.js')
                       ->appendFile('/js/dataTables.bootstrap.js')
                       ->appendFile('/js/cobalt/company/index.js');
?>
        
    <div class="row">
        <div class="col col-md-12 title">
            <h1>Companies</h1>
            <a class="btn btn-success btn-sm pull-right" href="<?php echo $this->url('cobalt/default', array('controller' => 'company', 'action' => 'add'));?>">
                <i class="fa fa-plus"></i> New Company</a>
            <hr>
        </div>
        <div class="col-md-12">
            <table id="companies" class="table table-bordered table-condensed table-cobalt" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th></th>
                        <th>Company</th>
                        <th>Address</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->companies as $company): ?> 
                    <tr>
                        <th style="width: 1%;" nowrap>
                            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'company', 'action' => 'edit', 'id' => $company->getId()));?>"><i class="fa fa-edit"></i></a>
                            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'company', 'action' => 'delete', 'id' => $company->getId()));?>"><i class="fa fa-remove"></i></a>
                        </th>
                        <td><a href="<?php echo $this->url('cobalt/default', array('controller' => 'company', 'action' => 'detail', 'id' => $company->getId()));?>">
                            <?php echo $company->getName();?></a></td>
                        <td><?php echo nl2br($company->getAddress());?></td>
                        
                    </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>

