<?php
    $this->headScript()->appendFile('/js/jquery-jvectormap-2.0.3.min.js')
                       ->appendFile('/js/jquery-jvectormap-world-mill-en.js');
    $this->headLink()->appendStylesheet('/css/jquery-jvectormap-2.0.3.css');
?>

    <div class="row">
        <div class="title col-lg-12">
            <h1>Dashboard</h1>
            <hr>
        </div>
    </div>

    <div class="row">

        <div class="col-lg-3 col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-desktop fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge"><?php echo $this->hardwareCount;?></div>
                            <div>Hardware.</div>
                        </div>
                    </div>
                </div>
                <a href="<?php echo $this->url('cobalt/default', array('controller' => 'hardware'));?>">
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right">
                            <i class="fa fa-arrow-circle-right"></i>
                        </span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
            
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-green">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-users fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge"><?php echo $this->userCount;?></div>
                            <div>Users.</div>
                        </div>
                    </div>
                </div>
                <a href="<?php echo $this->url('cobalt/default', array('controller' => 'user'));?>">
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right">
                            <i class="fa fa-arrow-circle-right"></i>
                        </span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
            
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-yellow">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-cubes fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge"><?php echo $this->projectCount;?></div>
                            <div>Projects.</div>
                        </div>
                    </div>
                </div>
                <a href="<?php echo $this->url('cobalt/default', array('controller' => 'planning'));?>">
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right">
                            <i class="fa fa-arrow-circle-right"></i>
                        </span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
            
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-red">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-cloud fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge"><?php echo $this->domainCount;?></div>
                            <div>Domains</div>
                        </div>
                    </div>
                </div>
                <a href="<?php echo $this->url('cobalt/default', array('controller' => 'domain'));?>">
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right">
                            <i class="fa fa-arrow-circle-right"></i>
                        </span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-red">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-ticket fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge"><?php echo $this->ticketCount;?></div>
                            <div>Support Tickets</div>
                        </div>
                    </div>
                </div>
                <a href="<?php echo $this->url('cobalt/default', array('controller' => 'ticket'));?>">
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right">
                            <i class="fa fa-arrow-circle-right"></i>
                        </span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        
        <div class="col-md-6">
            <div id="world-map" style="width: 600px; height: 400px"></div>
            <script>
                $(function(){
                    $('#world-map').vectorMap({map: 'world_mill_en'});
                    var mapObject = $('#world-map').vectorMap('get', 'mapObject');
                    mapObject.setBackgroundColor('#aaa');
                });
            </script>
        </div>

        <div class="col-md-12">
            <table table table-condensed table-bordered>
                <tbody>
                    <tr>
                        <th></th>
                        <th>Name</th>
                        <th>Physical Address</th>
                        <th>DHCP Enabled</th>
                        <th>IPv4 Address</th>
                        <th>Default Gateway</th>
                    </tr>
                    <?php foreach($this->adapters as $adapter){
                        echo $this->partial('partial/network-adapter', array('adapter' => $adapter));
                    } ?>
                    </tbody>
            </table>
        </div>
    </div>
    
