<?php
function formatBytes($bytes, $precision = 2) { 
    $units = array('B', 'KB', 'MB', 'GB', 'TB');
    $bytes = max($bytes, 0); 
    $pow = floor(($bytes ? log($bytes) : 0) / log(1024)); 
    $pow = min($pow, count($units) - 1); 
    $bytes /= pow(1024, $pow);
    return round($bytes, $precision) . ' ' . $units[$pow];
} 

?>

<table class="table">
    <tbody>
        <tr>
            <th>Caption</th>
            <th>Location</th>
            <th>Capacity</th>
            <th>Speed</th>
            <th>Data Width</th>
            <th>Description</th>
        </tr>
        <?php foreach($this->memory as $memory): ?> 
        <tr>
            <td><?php echo $memory->Caption;?></td>
            <td><?php echo $memory->DeviceLocator;?></td>
            <td><?php echo formatBytes($memory->Capacity);?></td>
            <td><?php echo $memory->Speed .' MHz';?></td>
            <td><?php echo $memory->DataWidth .' bit';?></td>
            <td><?php echo $memory->Status;?></td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>
