<dl class="dl-horizontal">
    <dt>Description</dt><dd><?php echo strstr($this->os->Name, "|", true);?></dd>
    <dt>Version</dt><dd><?php echo $this->os->Version;?></dd>
    <dt>Build Number</dt><dd><?php echo $this->os->BuildNumber;?></dd>
    <dt>Service Pack Major Version</dt><dd><?php echo $this->os->ServicePackMajorVersion;?></dd>
    
    <dt>Product Id</dt><dd><?php echo $this->os->SerialNumber;?></dd>   
</dl>