<div class="row">
    <div class="col-md-4 col-md-offset-4">
        
        <div class="col-ms-12 text-center">
            <img class="logo" src="/img/cobalt-logo.png">
            <br>
            <h4>Cobalt Application</h4>
            <hr>
        </div>
        
        <div class="well">
            
            <h4 style="margin-top:0;" class="text-center">Sign In</h4>
            <form class="form">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon"><i class="fa fa-user fa-fw"></i></div>
                        <input type="text" class="form-control" id="exampleInputAmount" placeholder="Username">
                    </div>
                </div>    
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon"><i class="fa fa-lock fa-fw"></i></div>
                        <input type="text" class="form-control" id="exampleInputAmount" placeholder="Password">
                    </div>

                </div>
                <button type="submit" class="btn btn-block btn-primary">Login</button>
            </form>
        </div>
        
        <div class="col-ms-12 text-center">
            <hr>
            <small>Civray Software</small>
        </div>
        
    </div>
</div>