<?php
    $this->headLink()->appendStylesheet('/css/datatables.css');
    $this->headScript()->appendFile('/js/datatables.js')
                       ->appendFile('/js/bootstrap/tab.js')
                       ->appendFile('/js/jquery-plugin/stickytabs.js')
                       ->appendFile('/js/cobalt/software/detail.js');
?>

<div class="row">
    <div class="col-md-12 title">
            
        <h1>Software Details</h1>
        <hr>
            
        <i class="fa fa-building fa-3x pull-left"></i>
        <h4><?php echo $this->software->getName(); ?></h4>
        <p>
            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'software', 'action' => 'edit', 'id' => $this->software->getId())); ?>"><i class="fa fa-edit"></i></a>
            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'software', 'action' => 'delete', 'id' => $this->software->getId())); ?>"><i class="fa fa-remove"></i></a>
        </p>
        
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist" id="tabs">
            <li role="presentation" class="active"><a href="#details"        aria-controls="home"          role="tab" data-toggle="tab">Details</a></li>
            <li role="presentation"><a                href="#licenses"       aria-controls="licenses"      role="tab" data-toggle="tab">Licenses</a></li>
            <li role="presentation"><a                href="#installations"  aria-controls="installations" role="tab" data-toggle="tab">Installations</a></li>
            <li role="presentation"><a                href="#history"        aria-controls="history"       role="tab" data-toggle="tab">History</a></li>
        </ul>
        
        <!-- Tab panes -->
        <div class="tab-content">
            
            <!-- Details tab -->
            <div role="tabpanel" class="tab-pane active" id="details">
                <div class="row">
                    <div class="col-lg-6">
                        <table class="table table-condensed table-bordered">
                            <tbody>
                                <tr>
                                    <th style="width: 35%;">Name</th>
                                    <td><?php echo $this->software->getName(); ?></td>
                                </tr>
                                <tr>
                                    <th>Version</th>
                                    <td><?php echo $this->software->getVersion(); ?></td>
                                </tr>
                                <tr>
                                    <th>Manufacturer</th>
                                    <td><?php echo $this->software->getManufacturer()->getName(); ?></td>
                                </tr>
                                <tr>
                                    <th>Type</th>
                                    <td><?php echo $this->software->getType()->getName(); ?></td>
                                </tr>
                                <tr>
                                    <th>Category</th>
                                    <td><?php echo $this->software->getCategory()->getName(); ?></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            
            <!-- Licenses tab -->
            <div role="tabpanel" class="tab-pane" id="licenses">
                <table class="table table-bordered">
                    <tr>
                        <th></th>
                        <th>License Key</th>
                        <th>Installations Allowed</td>
                    </tr>
                    <?php foreach ($this->software->getLicenses() as $license): ?>
                    <tr>
                        <th style="width: 1%;" nowrap>
                            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'softwarelicense', 'action' => 'edit', 'id' => $license->getId()));?>">
                                <i class="fa fa-edit"></i></a>
                            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'softwarelicense', 'action' => 'delete', 'id' => $license->getId()));?>">
                                <i class="fa fa-remove"></i></a>
                        </th>
                        <td><?php echo $license->getLicenseKey();?></td>
                        <td><?php echo $license->getInstallationsAllowed();?></td>
                    </tr>
                    <?php endforeach; ?>
                </table>
                <a class="btn btn-default btn-sm" href="<?php echo $this->url('cobalt/default', array(
                    'controller' => 'softwarelicense',
                    'action' => 'add'
                )); ?>">Add License</a>
            </div>
            
            <!-- Installations tab -->
            <div role="tabpanel" class="tab-pane" id="installations">
                No installations to show yet.
            </div>
            
            <!-- History tab -->
            <div role="tabpanel" class="tab-pane" id="history">
                <?php echo $this->partial('application/partial/history_table.phtml', array('history' => $this->history));?>
            </div>
            
        </div>
        
    </div>
</div>