<?php $this->headScript()->appendFile('/js/jquery.are-you-sure.js')
                         ->appendFile('/js/cobalt/software/edit.js'); ?>

<div class="row">
    
    <div class="col-md-12 title">
        <h1>Edit Software</h1>
        <hr>
    </div>
    
    <div class="col-md-6">
        <?php
            $form = $this->form;
            $form->get('submit')->setLabel('Edit');
            $form->setAttribute('action', $this->url('cobalt/default', array('controller' => 'software', 'action' => 'edit', 'id' => $this->id)));
            $form->prepare();

            echo $this->form($form);
        ?>
        
    </div>
</div>