<?php
    $this->headLink()->appendStylesheet('/css/dataTables.bootstrap.css');
    $this->headScript()->appendFile('/js/jquery.dataTables.js')
                       ->appendFile('/js/dataTables.bootstrap.js')
                       ->appendFile('/js/cobalt/software/index.js');
?>
        
    <div class="row">
        <div class="col col-md-12 title">
            <h1>Software</h1>
            <a class="btn btn-success pull-right" href="<?php echo $this->url('cobalt/default', array('controller' => 'software', 'action' => 'add'));?>">New Software</a>
            <hr>
        </div>
        <div class="col-md-12">
            <table id="offices" class="table" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Version</th>
                        <th>Manufacturer</th>
                        <th>Install Count</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->software as $software): ?> 
                    <tr>
                        <td><a href="<?php echo $this->url('cobalt/default', array('controller' => 'software', 'action' => 'detail', 'id' => $software->getId()));?>">
                            <?php echo $software->getName();?></a></td>
                        <td><?php echo $software->getVersion();?></td>
                        <td><?php echo $software->getManufacturer()->getName();?></td>
                        <td><?php echo $software->getInstallationCount();?></td>
                        <td style="width: 1%;" nowrap>
                            <a class="btn btn-warning btn-sm" href="<?php echo $this->url('cobalt/default', array('controller' => 'software', 'action' => 'edit', 'id' => $software->getId()));?>">Edit</a>
                            <a class="btn btn-danger btn-sm" href="<?php echo $this->url('cobalt/default', array('controller' => 'software', 'action' => 'delete', 'id' => $software->getId()));?>">Delete</a>
                        </td>
                    </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>
