    <div class="row">
        <div class="col-md-12 title">
            <h1>Add new department</h1>
            <hr>
        </div>
        <div class="col-md-6">
            <?php
                $form = $this->form;
                $form->setAttribute('action', $this->url('cobalt/default', array(
                    'controller' => 'department',
                    'action' => 'add',
                    'id' => $this->companyId
                )));
                $form->prepare();
                echo $this->form()->openTag($form);
                echo $this->form($form);
                echo $this->form()->closeTag();
            ?>
        </div>
    </div>