<?php
function formatBytes($bytes, $precision = 2) { 
    $units = array('B', 'KB', 'MB', 'GB', 'TB');
    $bytes = max($bytes, 0); 
    $pow = floor(($bytes ? log($bytes) : 0) / log(1024)); 
    $pow = min($pow, count($units) - 1); 
    $bytes /= pow(1024, $pow);
    return round($bytes, $precision) . ' ' . $units[$pow];
} 

?>

    <!-- Breadcrumb -->
    <ul class="breadcrumb">
        <li><a href="<?php echo $this->url('cobalt');?>"><i class="fa fa-home"></i> Home</a></li>
        <li><a href="<?php echo $this->url('cobalt/default', array('controller' => 'computer'));?>"><i class="fa fa-angle-right"></i> Computers</a></li>
        <li><i class="fa fa-angle-right"></i> <?php echo $computer->getHostName();?></li>
    </ul>

    <div class="row">
        <div class="col-12">
            
        <h1>Computer Details</h1>
        <br>
        <h3><?php echo strtoupper($computer->getHostName());?></h1>
        <hr>
        </div>
    </div>
    
    <div class="row">
        
        <div class="col col-6">    
            <dl class="dl-horizontal">
                <dt>Hostname</dt><dd><?php echo $computer->getHostname();?></dd>
                <dt>Domain</dt><dd><?php echo $computer->getDomain();?></dd>
                <dt>Manufacturer</dt><dd><?php echo $computer->getManufacturer();?></dd>
                <dt>Model</dt><dd><?php echo $computer->getModel();?></dd>
                <dt>Serial Number</dt><dd><?php echo $computer->getSerialNumber();?></dd>
                <dt>Bios Version</dt><dd><?php echo $computer->getBiosVersion();?></dd>
                <dt>System Type</dt><dd><?php echo $computer->getSystemType();?></dd>
            </dl>
            <br>
            <a class="btn btn-primary" href="vnc://<?php echo $computer->getHostname();?>">VNC</a>
            <a class="btn btn-danger" href="rdp://<?php echo $computer->getHostname();?>">RDP</a>
            <a class="btn btn-default" href="cdollar://<?php echo $computer->getHostname();?>\c$">Browse Drive C:</a>
            <a class="btn btn-default" href="/assets/index/disk/<?php echo $computer->getHostname();?>">Scan Drives</a>
            <a class="btn btn-default" href="/assets/index/warranty/<?php echo $computer->getSerialNumber();?>">Tag Lookup</a>
        </div>
        <div class="col col-6">
            <img width="100%" src="/cobalt/computer/<?php echo trim($computer->getModel());?>.jpg">
        </div>
    </div>
    
    <div class="row">
        <div class="col col-6">
            <h3>Operating System</h3>
            <hr>
            <dl class="dl-horizontal">
                <dt>Name</dt><dd><?php echo $computer->getOsName();?></dd>
                <dt>Version</dt><dd><?php echo $computer->getOsVersion();?></dd>
                <dt>Build</dt><dd><?php echo $computer->getOsBuild();?></dd>
                <dt>Service Pack</dt><dd><?php echo $computer->getOsServicePack();?></dd>
                <br>

            </dl>
        </div>
        <div class="col col-6">

            <h3>Logical Disks</h1>
            <hr>
            <table class="table">
                <tbody>
                    <tr>
                        <th>Device Id</th>
                        <th>Description</th>
                        <th>File System</th>
                        <th>Capacity</th>
                        <th colspan="2">Free Space</th>

                    </tr>
                    <?php foreach($this->disks as $disk): ?> 
                    <tr>
                        <td><?php echo $disk->getDeviceId();?></td>
                        <td><?php echo $disk->getDescription();?></td>
                        <td><?php echo $disk->getFileSystem();?></td>
                        <td><?php echo formatBytes($disk->getCapacity());?></td>
                        <td width="100px"><?php echo formatBytes($disk->getFreeSpace());?></td>
                        <td width="200px">
                            <?php if ($disk->getCapacity() > 0): ?>
                            <div class="progress" width="200px" style="margin-bottom: 0;">
                                <div class="progress-bar <?php echo $disk->getFreeSpaceClass();?>" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="min-width: 12%; width: <?php echo $disk->getFreeSpacePercent(); ?>%;">
                                    <?php echo $disk->getFreeSpaceText(); ?>%
                                </div>
                            </div>
                            <?php endif; ?>

                        </td>

                    </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
            <br><br>
        </div>
    </div>