<?php
    $this->inlineScript()->appendFile('/js/bootstrap/tab.js')
                         ->appendFile('/js/jquery-plugin/stickytabs.js')
                         ->appendFile('/js/cobalt/computer/detail.js');

function formatBytes($bytes, $precision = 2) { 
    $units = array('B', 'KB', 'MB', 'GB', 'TB');
    $bytes = max($bytes, 0); 
    $pow = floor(($bytes ? log($bytes) : 0) / log(1024)); 
    $pow = min($pow, count($units) - 1); 
    $bytes /= pow(1024, $pow);
    return round($bytes, $precision) . ' ' . $units[$pow];
} 

?>

<div class="row">
    <div class="col-md-12 title">
            
        <h1>Computer Details</h1>
        <hr>
            
        <i class="fa fa-desktop fa-3x pull-left"></i>
        <h4><?php echo $this->computer->getHostname(); ?></h4>
        <p>
            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'computer', 'action' => 'edit', 'id' => $this->computer->getId())); ?>"><i class="fa fa-edit"></i></a>
        <a href="<?php echo $this->url('cobalt/default', array('controller' => 'computer', 'action' => 'delete', 'id' => $this->computer->getId())); ?>"><i class="fa fa-remove"></i></a>
        <span id="status"></span>
        </p>
        
    
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist" id="tabs">
            <li role="presentation" class="active"><a href="#details" aria-controls="home"    role="tab" data-toggle="tab">Details</a></li>
            <li role="presentation"><a href="#os"               aria-controls="os"               role="tab" data-toggle="tab">Operating System</a></li>
            <li role="presentation"><a href="#disks"            aria-controls="disks"            role="tab" data-toggle="tab">Logical Disks</a></li>
            <li role="presentation"><a href="#network-adapters" aria-controls="network-adapters" role="tab" data-toggle="tab">Network Adapters</a></li>
            <li role="presentation"><a href="#relationships"    aria-controls="relationships"    role="tab" data-toggle="tab">Relationships</a></li>
            <li role="presentation"><a href="#history"          aria-controls="history"          role="tab" data-toggle="tab">History</a></li>
        </ul>
        
        <!-- Tab panes -->
        <div class="tab-content">

            <!-- Details tab -->
            <div role="tabpanel" class="tab-pane active" id="details">
                <div class="row">
                    <div class="col-lg-6">
                        <table class="table table-condensed table-bordered">
                            <tbody>
                                <tr>
                                    <th style="width: 35%;">Hostname</th>
                                    <td><?php echo $this->computer->getHostname(); ?></td>
                                </tr>
                                 <tr>
                                    <th style="width: 35%;">Domain</th>
                                    <td><?php echo $this->computer->getDomain(); ?></td>
                                </tr>
                                <tr>
                                    <th>Manufacturer</th>
                                    <td><?php echo $this->computer->getManufacturer()->getName(); ?></td>
                                </tr>
                                <tr>
                                    <th>Model</th>
                                    <td><?php echo $this->computer->getModel(); ?></td>
                                </tr>
                                <tr>
                                    <th>Serial No</th>
                                    <td><?php echo $this->computer->getSerialNumber(); ?></td>
                                </tr>
                                <tr>
                                    <th style="width: 35%;">Bios Version</th>
                                    <td><?php echo $this->computer->getBiosVersion(); ?></td>
                                </tr>
                                 <tr>
                                    <th style="width: 35%;">System Type</th>
                                    <td><?php echo $this->computer->getSystemType(); ?></td>
                                </tr>
                                <tr>
                                    <th>Purchase Date</th>
                                    <td></td>
                                </tr>
                                <tr>
                                    <th>Warranty End</th>
                                    <td></td>
                                </tr>
                                <tr>
                                    <th>Service Tag</th>
                                    <td></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                    
                    <div class="col col-md-4">
                    <?php if ($computer->getImage() <> ''): ?>
                        <img width="100%" src="/cobalt/computer/<?php echo trim($computer->getImage());?>">
                    <?php else: ?>
                        <div width="100%" class="text-center">No Image</div>
                    <?php endif; ?>
                    </div>
                </div>
            </div>

            <!-- Operating system tab -->
            <div role="tabpanel" class="tab-pane" id="os">
                <div class="row">
                    <div class="col-lg-6">
                        <table class="table table-condensed table-bordered">
                            <tbody>
                                <tr>
                                    <th style="width: 35%;">Operating System</th>
                                    <td><?php echo $this->computer->getOSName(); ?></td>
                                </tr>
                                 <tr>
                                    <th>Version</th>
                                    <td><?php echo $this->computer->getOSVersion(); ?></td>
                                </tr>
                                <tr>
                                    <th>Build Number</th>
                                    <td><?php echo $this->computer->getOSBuild(); ?></td>
                                </tr>
                                <tr>
                                    <th>Service Pack</th>
                                    <td><?php echo $this->computer->getOSServicePack(); ?></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            
            <!-- Disk tab -->
            <div role="tabpanel" class="tab-pane" id="disks">
                <table class="table">
                <tbody>
                    <tr>
                        <th>Device Id</th>
                        <th>Description</th>
                        <th>File System</th>
                        <th>Capacity</th>
                        <th colspan="2">Free Space</th>
                    </tr>
                    <?php foreach($computer->getLogicalDisks() as $disk): ?> 
                        <tr>
                            <td><?php echo $disk->getDeviceId();?></td>
                            <td><?php echo $disk->getDescription();?></td>
                            <td><?php echo $disk->getFileSystem();?></td>
                            <td><?php echo formatBytes($disk->getCapacity());?></td>
                            <td width="100px"><?php echo formatBytes($disk->getFreeSpace());?></td>
                            <td width="200px">
                            <?php if ($disk->getCapacity() > 0): ?>
                            <div class="progress" width="200px" style="margin-bottom: 0;">
                                <div class="progress-bar <?php echo $disk->freeSpaceClass();?>" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="min-width: 12%; width: <?php echo $disk->freeSpacePercent(); ?>%;">
                                    <?php echo $disk->freeSpaceText(); ?>%
                                </div>
                            </div>
                            <?php endif; ?>

                            </td>

                        </tr>
                    <?php endforeach ?>
                    </tbody>
                </table>
            </div>
            
            <!-- Network Adapters tab -->
            <div role="tabpanel" class="tab-pane" id="network-adapters">
                <table class="table table-condensed table-bordered">
                <tbody>
                    <tr>
                        <th></th>
                        <th>Name</th>
                        <th>Physical Address</th>
                        <th>DHCP Enabled</th>
                        <th>IPv4 Address</th>
                        <th>Default Gateway</th>
                    </tr>
                    <?php foreach($computer->getNetworkAdapters() as $adapter): ?> 
                        <tr>
                            <td style="width: 1%;" nowrap>
                                    <a href="<?php echo $this->url('cobalt/default', array('controller' => 'NetworkAdapter', 'action' => 'edit', 'id' => $adapter->getId()));?>">
                                        <i class="fa fa-edit"></i></a>
                                    <a href="<?php echo $this->url('cobalt/default', array('controller' => 'NetworkAdapter', 'action' => 'delete', 'id' => $adapter->getId()));?>">
                                        <i class="fa fa-remove"></i></a>
                                </td>
                            <td><?php echo $adapter->getName();?></td>
                            <td><?php echo $adapter->getPhysicalAddress();?></td>
                            <td><?php echo $adapter->getDhcpEnabled();?></td>
                            <td><?php echo $adapter->getIpv4Address();?></td>
                            <td><?php echo $adapter->getDefaultGateway();?></td>
                        </tr>
                    <?php endforeach ?>
                    </tbody>
                </table>
                <a class="btn btn-default btn-sm" href="<?php echo $this->url('cobalt/default', array(
                    'controller' => 'networkadapter',
                    'action'     => 'add',
                    'id'         => $this->computer->getId()
                ));?>">Add Adapter</a>
            </div>

            <!-- Relationships tab -->
            <div role="tabpanel" class="tab-pane" id="relationships">
                    
            </div>
            
            <!-- History tab -->
            <div role="tabpanel" class="tab-pane" id="history">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Date & Time</th>
                            <th>Event</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->history as $history): ?>
                        <tr>
                            <td><?php echo $history->getTime()->format('d/m/Y h:i:s');?></td>
                            <td><?php echo $history->getEvent(); ?></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
    
        </div>
        
    </div>
</div>

<div class="col-lg-12">
    <br>
    <a class="btn btn-primary" href="vnc://<?php echo $computer->getHostname();?>">VNC</a>
    <a class="btn btn-danger" href="rdp://<?php echo $computer->getHostname();?>">RDP</a>
    <a class="btn btn-default" href="cdollar://<?php echo $computer->getHostname();?>\c$">Browse Drive C:</a>
    <a class="btn btn-default" href="<?php echo $this->url('cobalt/default', array(
        'controller' => 'computer',
        'action'     => 'scan',
        'id'         => $this->computer->getId()
    )); ?>">Scan</a>
    <a class="btn btn-default" href="<?php echo $this->url('cobalt/default', array(
        'controller' => 'computer',
        'action'     => 'scandisks',
        'id'         => $this->computer->getId()
    )); ?>">Scan Drives</a>
    <a class="btn btn-default" href="/assets/index/warranty/<?php echo $computer->getSerialNumber();?>">Tag Lookup</a>
</div>



