<?php
    $this->inlineScript()->appendFile('/js/cobalt/computer/edit.js');
?>

<div class="row">
    
    <div class="col-md-12 title">
        <h1>Edit Computer</h1>
        <hr>
      
    </div>

    <div class="col-md-10">
        <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('cobalt/default', array(
                'controller' => 'computer',
                    'action' => 'edit',
                    'id'     => $this->id
                )));
            $form->prepare();
            echo $this->form()->openTag($form);
            echo $this->form($form);
            echo $this->form()->closeTag();
        ?>
    </div>
    
</div>