<?php $this->headScript()->appendFile('/js/jquery.are-you-sure.js')
                         ->appendFile('/js/cobalt/consumable/edit.js'); ?>

<div class="row">
    
    <div class="col-md-12 title">
        <h1>Edit Consumable</h1>
        <hr>
      
    </div>

    <div class="col-md-10">
        <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('cobalt/default', array(
                'controller' => 'consumable',
                    'action' => 'edit',
                    'id'     => $this->id
                )));
            $form->prepare();
            echo $this->form()->openTag($form);
            echo $this->form($form);
            echo $this->form()->closeTag();
        ?>
    </div>
    
</div>