<?php
    $this->headLink()->appendStylesheet('/css/dataTables.bootstrap.css');
    $this->headScript()->appendFile('/js/jquery.dataTables.js')
                       ->appendFile('/js/dataTables.bootstrap.js')
                       ->appendFile('/js/cobalt/consumable/index.js');
?>
        
    <div class="row">
        <div class="col col-md-12 title">
            <h1>Consumables</h1>
            <a class="btn btn-success btn-sm pull-right" href="<?php echo $this->url('cobalt/default', array('controller' => 'consumable', 'action' => 'add'));?>">
                <i class="fa fa-plus"></i> New Consumable</a>
            <hr>
        </div>
        <div class="col-md-12">
            <table id="consumables" class="table table-bordered table-cobalt" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th></th>
                        <th>Name</th>
                        <th>Supplier</th>
                        <th>Qty In Stock</th>
                        <th>Reorder Qty</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->consumables as $consumable): ?> 
                    <tr>
                        <td style="width: 1%;" nowrap>
                            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'consumable', 'action' => 'edit', 'id' => $consumable->getId()));?>"><i class="fa fa-edit"></i></a>
                            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'consumable', 'action' => 'delete', 'id' => $consumable->getId()));?>"><i class="fa fa-remove"></i></a> 
                        </td>
                        <td><a href="<?php echo $this->url('cobalt/default', array('controller' => 'consumable', 'action' => 'detail', 'id' => $consumable->getId()));?>">
                            <?php echo $consumable->getName();?></a></td>
                        <td><?php echo $consumable->getSupplier();?></td>
                        <td><?php echo $consumable->getQtyInStock();?></td>
                        <td><?php echo $consumable->getReorderQty();?></td>    
                    </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>