<tr>
    <td style="width: 1%;" nowrap>
            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'network-adapter', 'action' => 'edit', 'id' => $adapter->getId()));?>">
                <i class="fa fa-edit"></i></a>
            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'network-adapter', 'action' => 'delete', 'id' => $adapter->getId()));?>">
                <i class="fa fa-remove"></i></a>
        </td>
    <td><?php echo $adapter->getName();?></td>
    <td><?php echo $adapter->getPhysicalAddress();?></td>
    <td><?php echo $adapter->getDhcpEnabled();?></td>
    <td>
        <span style="display: inline-block; width: 110px;"><?php echo $adapter->getIpv4Address();?></span>
        <?php if($adapter->getStatus() == 'alive'): ?>
        <span class="label label-success">Online</span>
        <?php else: ?>
        <span class="label label-danger">Offline</span>
        <?php endif; ?>
    </td>
    <td><?php echo $adapter->getDefaultGateway();?></td>
</tr>