<?php
    $this->headLink()->appendStylesheet('/css/datatables.css');
    $this->headScript()->appendFile('/js/datatables.js')
                       ->appendFile('/js/bootstrap/tab.js')
                       ->appendFile('/js/jquery-plugin/stickytabs.js')
                       ->appendFile('/js/cobalt/printer/detail.js');
?>

<div class="row">
    <div class="col-md-12 title">
            
        <h1>Printer Details</h1>
        <hr>
            
        <i class="fa fa-print fa-3x pull-left"></i>
        <h4><?php echo $this->printer->getReference(); ?></h4>
        <p>
            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'printer', 'action' => 'edit', 'id' => $this->printer->getId())); ?>"><i class="fa fa-edit"></i></a>
            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'printer', 'action' => 'delete', 'id' => $this->printer->getId())); ?>"><i class="fa fa-remove"></i></a>
        </p>
        
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist" id="tabs">
            <li role="presentation" class="active"><a href="#details" aria-controls="home"    role="tab" data-toggle="tab">Details</a></li>
            <li role="presentation"><a href="#history"                aria-controls="history" role="tab" data-toggle="tab">History</a></li>
        </ul>
        
        <!-- Tab panes -->
        <div class="tab-content">
            
            <!-- Details tab -->
            <div role="tabpanel" class="tab-pane active" id="details">
                <div class="row">
                    <div class="col-lg-6">
                        <table class="table table-condensed table-bordered">
                            <tbody>
                                <tr>
                                    <th style="width: 35%;">Unique Reference</th>
                                    <td><?php echo $this->printer->getReference(); ?></td>
                                </tr>
                                <tr>
                                    <th>Type</th>
                                    <td><?php echo $this->printer->getType()->getName(); ?></td>
                                </tr>
                                <tr>
                                    <th>Status</th>
                                    <td><?php echo $this->printer->getStatus()->getName(); ?></td>
                                </tr>
                                <tr>
                                    <th>Model</th>
                                    <td><?php echo $this->printer->getModel(); ?></td>
                                </tr>
                                <tr>
                                    <th>Serial Number</th>
                                    <td><?php echo $this->printer->getSerialNumber(); ?></td>
                                </tr>
                                <tr>
                                    <th>Manufacturer</th>
                                    <td><?php echo $this->printer->getManufacturer()->getName(); ?></td>
                                </tr>
                                <tr>
                                    <th>Asset Number</th>
                                    <td><?php echo nl2br($this->printer->getAssetNumber()); ?></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            
            <!-- History tab -->
            <div role="tabpanel" class="tab-pane" id="history">
                No history to show yet.
            </div>
            
        </div>
        
    </div>
</div>