<?php
    $this->headLink()->appendStylesheet('/css/datatables.css');
    $this->headScript()->appendFile('/js/datatables.js')
                       ->appendFile('/js/bootstrap/tab.js')
                       ->appendFile('/js/jquery-plugin/stickytabs.js')
                       ->appendFile('/js/cobalt/printer/detail.js');
?>

<div class="row">
    <div class="col-md-12 title">
            
        <h1>Printer Details</h1>
        <hr>
            
        <i class="fa fa-print fa-3x pull-left"></i>
        <h4><?php echo $this->printer->getReference(); ?></h4>
        <p>
            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'printer', 'action' => 'edit', 'id' => $this->printer->getId())); ?>"><i class="fa fa-edit"></i></a>
            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'printer', 'action' => 'delete', 'id' => $this->printer->getId())); ?>"><i class="fa fa-remove"></i></a>
        </p>
        
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist" id="tabs">
            <li role="presentation" class="active"><a href="#details" aria-controls="home"             role="tab" data-toggle="tab">Details</a></li>
            <li role="presentation"><a href="#consumables"            aria-controls="consumables"      role="tab" data-toggle="tab">Consumables</a></li>
            <li role="presentation"><a href="#network-adapters"       aria-controls="network-adapters" role="tab" data-toggle="tab">Network Adapters</a></li>
            <li role="presentation"><a href="#history"                aria-controls="history"          role="tab" data-toggle="tab">History</a></li>
        </ul>
        
        <!-- Tab panes -->
        <div class="tab-content">
            
            <!-- Details tab -->
            <div role="tabpanel" class="tab-pane active" id="details">
                <div class="row">
                    <div class="col-lg-6">
                        <table class="table table-condensed table-bordered">
                            <tbody>
                                <tr>
                                    <th style="width: 35%;">Unique Reference</th>
                                    <td><?php echo $this->printer->getReference(); ?></td>
                                </tr>
                                <tr>
                                    <th>Type</th>
                                    <td><?php echo $this->printer->getType()->getName(); ?></td>
                                </tr>
                                <tr>
                                    <th>Status</th>
                                    <td><?php echo $this->printer->getStatus()->getName(); ?></td>
                                </tr>
                                <tr>
                                    <th>Model</th>
                                    <td><?php echo $this->printer->getModel(); ?></td>
                                </tr>
                                <tr>
                                    <th>Serial Number</th>
                                    <td><?php echo $this->printer->getSerialNumber(); ?></td>
                                </tr>
                                <tr>
                                    <th>Manufacturer</th>
                                    <td><?php echo $this->printer->getManufacturer()->getName(); ?></td>
                                </tr>
                                <tr>
                                    <th>Asset Number</th>
                                    <td><?php echo nl2br($this->printer->getAssetNumber()); ?></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="col-lg-6">
                        <table class="table table-condensed table-bordered">
                            <tbody>
                                <tr>
                                    <th style="width: 35%;">Technology</th>
                                    <td><?php echo $this->printer->getTechnology(); ?></td>
                                </tr>
                                <tr>
                                    <th>Resolution</th>
                                    <td><?php echo $this->printer->getResolution(); ?></td>
                                </tr>
                                <tr>
                                    <th>Quality</th>
                                    <td><?php echo $this->printer->getQuality(); ?></td>
                                </tr>
                                <tr>
                                    <th>Print Speed</th>
                                    <td><?php echo $this->printer->getSpeed(); ?></td>
                                </tr>
                                <tr>
                                    <th>Duty Cycle</th>
                                    <td><?php echo $this->printer->getDutyCycle(); ?></td>
                                </tr>
                                
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            
            <!-- Consumables tab -->
            <div role="tabpanel" class="tab-pane" id="consumables">
                <table class="table table-condensed table-bordered">
                <tbody>
                    <tr>
                        <th></th>
                        <th>Name</th>
                        <th>Type</th>
                        <th>Supplier</th>
                        <th>Qty In Stock</th>
                        <th>Reorder Qty</th>
                    </tr>
                    <?php foreach($this->printer->getConsumables() as $consumable): ?>
                    <tr>
                        <td class="text-center" style="width: 1%; padding-right:10px;" nowrap>
                            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'printer', 'action' => 'removeconsumable', 'id' => $this->printer->getId() . '_' . $consumable->getId()));?>"><i class="fa fa-remove"></i></a>
                        </td>
                        <td><?php echo $consumable->getName(); ?></td>
                        <td><?php echo $consumable->getType(); ?></td>
                        <td><?php echo $consumable->getSupplier(); ?></td>
                        <td><?php echo $consumable->getQtyInStock(); ?></td>
                        <td><?php echo $consumable->getReorderQty(); ?></td>
                    </tr>                    
                    <?php endforeach; ?>
                    </tbody>
                </table>
                <a class="btn btn-default btn-sm" href="<?php echo $this->url('cobalt/default', array(
                    'controller' => 'printer',
                    'action'     => 'addconsumable',
                    'id'         => $this->printer->getId()
                ));?>">Add Consumable</a>
            </div>
            
            <!-- Network Adapters tab -->
            <div role="tabpanel" class="tab-pane" id="network-adapters">
                <table class="table table-condensed table-bordered">
                <tbody>
                    <tr>
                        <th></th>
                        <th>Name</th>
                        <th>Physical Address</th>
                        <th>DHCP Enabled</th>
                        <th>IPv4 Address</th>
                        <th>Default Gateway</th>
                    </tr>
                    <?php foreach($printer->getNetworkAdapters() as $adapter){ 
                        echo $this->partial('partial/network-adapter', array('adapter' => $adapter));
                    } ?>
                    </tbody>
                </table>
                <a class="btn btn-default btn-sm" href="<?php echo $this->url('cobalt/default', array(
                    'controller' => 'NetworkAdapter',
                    'action'     => 'add',
                    'id'         => $this->printer->getId()
                ));?>">Add Adapter</a>
            </div>
            
            <!-- History tab -->
            <div role="tabpanel" class="tab-pane" id="history">
                No history to show yet.
            </div>
            
        </div>
        
    </div>
</div>