<?php
    $this->headLink()->appendStylesheet('/css/dataTables.bootstrap.css');
    $this->headScript()->appendFile('/js/jquery.dataTables.js')
                       ->appendFile('/js/dataTables.bootstrap.js')
                       ->appendFile('/js/cobalt/printer/index.js');
?>
        
    <div class="row">
        <div class="col col-md-12 title">
            <h1>Printers</h1>
            <a class="btn btn-success pull-right" href="<?php echo $this->url('cobalt/default', array('controller' => 'printer', 'action' => 'add'));?>">New Printer</a>
            <hr>
        </div>
        <div class="col-md-12">
            <table id="printers" class="table table-bordered table-condensed table-cobalt" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th></th>
                        <th>Unique Reference</th>
                        <th>Technology</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->printers as $printer): ?> 
                    <tr>
                        <td style="width: 1%;" nowrap>
                            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'printer', 'action' => 'edit', 'id' => $printer->getId()));?>"><i class="fa fa-edit"></i></a>
                            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'printer', 'action' => 'delete', 'id' => $printer->getId()));?>"><i class="fa fa-remove"></i></a>
                        </td>
                        <td><a href="<?php echo $this->url('cobalt/default', array('controller' => 'printer', 'action' => 'detail', 'id' => $printer->getId()));?>">
                            <?php echo $printer->getReference();?></a></td>
                        <td><?php echo $printer->getTechnology();?></td>
                        
                    </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>