<?php
    $this->headLink()->appendStylesheet('/css/dataTables.bootstrap.css');
    $this->headScript()->appendFile('/js/jquery.dataTables.js')
                       ->appendFile('/js/dataTables.bootstrap.js')
                       ->appendFile('/js/cobalt/hardwaremanufacturer/index.js');
?>
        
    <div class="row">
        <div class="col col-md-12 title">
            <h1>Hardware Manufacturers</h1>
            <a class="btn btn-sm btn-success pull-right" href="<?php echo $this->url('cobalt/default', array('controller' => 'hardware-manufacturer', 'action' => 'add'));?>">New Manufacturer</a>
            <hr>
        </div>
        <div class="col-md-12">
            <table id="manufacturers" class="table table-bordered table-cobalt" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th></th>
                        <th>Name</th>
                        <th>Address</th>
                        <th>Email</th>
                        <th>Website</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->manufacturers as $manufacturer): ?> 
                    <tr>
                        <td style="width: 1%;" nowrap>
                            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'hardware-manufacturer', 'action' => 'edit', 'id' => $manufacturer->getId()));?>"><i class="fa fa-edit"></i></a>
                            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'hardware-manufacturer', 'action' => 'delete', 'id' => $manufacturer->getId()));?>"><i class="fa fa-remove"</a>
                        </td>
                        <td><a href="<?php echo $this->url('cobalt/default', array('controller' => 'hardware-manufacturer', 'action' => 'detail', 'id' => $manufacturer->getId()));?>">
                            <?php echo $manufacturer->getName();?></a></td>
                        <td><?php echo nl2br($manufacturer->getAddress());?></td>
                        <td><?php echo $manufacturer->getEmail();?></td>
                        <td><a target="_blank" href="<?php echo $manufacturer->getWebsiteUrl(); ?> ">
                            <?php echo $manufacturer->getWebsiteUrl();?>
                        </a></td>
                    </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>