<?php $this->headScript()->appendFile('/js/jquery.are-you-sure.js')
                         ->appendFile('/js/cobalt/software-type/edit.js'); ?>
    <div class="row">
        <div class="col-md-12 title">
            <h1>Edit software type</h1>
            <hr>
        </div>
        <div class="col-md-6">
            <?php
                $form = $this->form;
                $form->setAttribute('action', $this->url('cobalt/default', array(
                    'controller' => 'softwaretype',
                    'action'     => 'edit',
                    'id'         => $this->id)));
                $form->get('submit')->setLabel('Edit');
                $form->prepare();
                echo $this->form()->openTag($form);
                echo $this->form($form);
                echo $this->form()->closeTag();
            ?>
        </div>
    </div>  