<div class="row">
    
    <div class="col-md-12 title">
        <h1>Create new project</h1>
        <hr>
      
    </div>
    
    <div class="col-md-12">
        <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('project/default', array('controller' => 'project', 'action' => 'add')));
            $form->prepare();

            echo $this->form($form);
        ?>
        
    </div>
</div>

