<?php
    $this->headLink()->appendStylesheet('/css/datatables.css');
    $this->headScript()->appendFile('/js/datatables.js')
                       ->appendFile('/js/bootstrap/tab.js')
                       ->appendFile('/js/project/project/detail.js');
?>

<div class="row">
    <div class="col-md-12 title">
        <h1>Project Details</h1>
        <hr>
        
        <h4><?php echo $this->project->getName(); ?></h4>
        <p>
            <a href="#"><i class="fa fa-edit"></i></a>
            <a href="#"><i class="fa fa-remove"></i></a>
        </p>
        
        <div>
            <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist" id="tabs">
                <li role="presentation" class="active"><a href="#detail" aria-controls="home" role="tab" data-toggle="tab">Detail</a></li>
                <li role="presentation"><a href="#milestones" aria-controls="milestones" role="tab" data-toggle="tab">Milestones</a></li>
                <li role="presentation"><a href="#tasks" aria-controls="tasks" role="tab" data-toggle="tab">Tasks</a></li>
                <li role="presentation"><a href="#history" aria-controls="history" role="tab" data-toggle="tab">History</a></li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content">
                
                <!-- Project details tab -->
                <div role="tabpanel" class="tab-pane active" id="detail">
                    <div class="row">
                        
                        <div class="col-lg-6">
                            <table class="table table-condensed table-bordered">
                                <tbody>
                                    <tr>
                                        <th style="width: 35%;">Code</th>
                                        <td><?php echo $this->project->getCode(); ?></td>
                                    </tr>
                                     <tr>
                                        <th style="width: 35%;">Name</th>
                                        <td><?php echo $this->project->getName(); ?></td>
                                    </tr>
                                    <tr>
                                        <th>Description</th>
                                        <td><?php echo $this->project->getDescription(); ?></td>
                                    </tr>
                                    <tr>
                                        <th>Estimated Hours</th>
                                        <td><?php echo $this->project->getEstimatedHours(); ?></td>
                                    </tr>
                                    <tr>
                                        <th>Estimated Cost</th>
                                        <td><?php echo $this->project->getEstimatedCost(); ?></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        
                        <div class="col-lg-6">
                            <table class="table table-condensed table-bordered">
                                <tbody>
                                    <tr>
                                        <th style="width: 35%;">Status</th>
                                        <td><div class="status status-blue"><?php echo $this->project->getStatus()->getName(); ?></div></td>
                                    </tr>
                                    <tr>
                                        <th>Owner</th>
                                        <td>Fred Bloggs</td>
                                    </tr>
                                    <tr>
                                        <th>Priority</th>
                                        <td><div class="status status-red"><?php echo $this->project->getPriority()->getName(); ?></div></td>
                                    </tr>
                                    <tr>
                                        <th>Actual Hours</th>
                                        <td><?php echo $this->project->getActualHours(); ?></td>
                                    </tr>
                                    <tr>
                                        <th>Actual Cost</th>
                                        <td><?php echo $this->project->getActualCost(); ?></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        
                    </div>
                </div>
                
                <!-- Milestones tab -->
                <div role="tabpanel" class="tab-pane" id="milestones">
                    <div class="row">
                        <div class="col-md-12">
                            <table class="table table-condensed">
                                <tr>
                                    <th>Name</th>
                                    <th>Description</th>
                                    <th>Status</th>
                                    <th>Priority</th>
                                </tr>
                                <?php foreach ($this->project->getMilestones() as $milestone): ?>
                                <tr>
                                    <td><?php echo $milestone->getName(); ?></td>
                                    <td><?php echo $milestone->getDescription(); ?></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                <?php endforeach; ?>
                            </table>
                            <a class="btn btn-default btn-sm" href="<?php echo $this->url('project/default', array(
                                'controller' => 'milestone',
                                'action' => 'add',
                                'id' => $this->project->getId()
                            )) ?>">Add Milestone</a>
                        </div>
                    </div>                    
                </div>
                
                <!-- Tasks tab -->
                <div role="tabpanel" class="tab-pane" id="tasks">
                    Tasks
                </div>
                
                <!-- History tab -->
                <div role="tabpanel" class="tab-pane" id="history">
                    History
                </div>
            </div>

        </div>
        
    </div>
</div>
