<div class="row">
    <div class="col-md-12 title">
        <h1>Project Details</h1>
        <hr>
        
        <br>
        <b>Project: </b><span><?php echo $this->project->getName(); ?></span>
        <br>
        
        
        
        
        <div>
            <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active"><a href="#detail" aria-controls="home" role="tab" data-toggle="tab">Detail</a></li>
                <li role="presentation"><a href="#profile" aria-controls="milestones" role="tab" data-toggle="tab">Milestones</a></li>
                <li role="presentation"><a href="#messages" aria-controls="tasks" role="tab" data-toggle="tab">Tasks</a></li>
                <li role="presentation"><a href="#settings" aria-controls="history" role="tab" data-toggle="tab">History</a></li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="detail">...</div>
                <div role="tabpanel" class="tab-pane" id="milestones">...</div>
                <div role="tabpanel" class="tab-pane" id="tasks">...</div>
                <div role="tabpanel" class="tab-pane" id="history">...</div>
            </div>

        </div>
        
        
        
        
        
        
        
        
        <br>
        <b>Milestones</b><br>
        <table>
            <?php foreach ($this->project->getMilestones() as $milestone): ?>
            <tr>
                <td><?php echo $milestone->getName(); ?></td>
            </tr>
            <?php endforeach; ?>
        </table>
        <a class="btn btn-action" href="<?php echo $this->url('project/default', array(
            'controller' => 'milestone',
            'action' => 'add',
            'id' => $this->project->getId()
        )) ?>">New Milestone</a>
    </div>
</div>
