<?php
    $this->headLink()->appendStylesheet('/css/dataTables.bootstrap.css');
    $this->headScript()->appendFile('/js/jquery.dataTables.js')
                       ->appendFile('/js/dataTables.bootstrap.js')
                       ->appendFile('/js/project/project/index.js');
?>

    <div class="row">
        <div class="col-md-12 title">
            <h1 class=>Projects</h1>
            <a class="btn btn-success btn-sm pull-right" href="<?php echo $this->url('project/default', array('controller' => 'project', 'action' => 'add'));?>">
                <i class="fa fa-cubes"></i> New Project</a>
            <hr>
        </div>
        <div class="col-md-12">
            <table id="projects" class="table" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Status</th>
                        <th>Priority</th>
                        <th>Scheduled Start</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->projects as $project): ?>
                    <tr>
                        <td><a href="<?php echo $this->url('project/default', array(
                            'controller' => 'project',
                            'action' => 'detail',
                            'id' => $project->getId()
                        )); ?>">
                            <?php echo $project->getName(); ?>
                        </a></td>
                        <td><?php echo $project->getStatus()->getName(); ?></td>
                        <td><?php echo $project->getPriority()->getName(); ?></td>
                        <td><?php echo $project->getScheduledStart(); ?></td>
                        <td style="width: 1%;" nowrap>
                            <a class="btn btn-warning btn-sm" href="<?php echo $this->url('project/default', array('controller' => 'project', 'action' => 'edit', 'id' => $project->getId()));?>">Edit</a>
                            <a class="btn btn-danger btn-sm" href="<?php echo $this->url('project/default', array('controller' => 'project', 'action' => 'delete', 'id' => $project->getId()));?>">Delete</a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>