<div class="row">
    <div class="col-md-12 title">
        <h1>Delete Support Ticket Status</h1>
        <hr>
        <p>Are you sure you want to delete the support ticket status <i><b><?php echo $this->status->getName(); ?></b></i> ?</p>
        
        <form action="<?php echo $this->url('cobalt/default', array(
            'controller' => 'ticketstatus',
            'action' => 'delete',
            'id' => $this->status->getId()
        )); ?>" method="post">
            <div>
                <input class="btn btn-primary" type="submit" name="del" value="Yes" />
                <input class="btn btn-default" type="submit" name="del" value="No" />
            </div>
        </form>
    </div>
</div>