
<div class="row">
    <div class="col-md-12 title">
            
        <h1>Domain Details</h1>
        <hr>
            
        <i class="fa fa-cloud fa-3x pull-left"></i>
        <h4><?php echo $this->domain->getName(); ?></h4>
        <p>
            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'domain', 'action' => 'edit', 'id' => $this->domain->getId())); ?>"><i class="fa fa-edit"></i></a>
        <a href="<?php echo $this->url('cobalt/default', array('controller' => 'domain', 'action' => 'delete', 'id' => $this->domain->getId())); ?>"><i class="fa fa-remove"></i></a>
        </p>
        
    
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist" id="tabs">
            <li role="presentation" class="active"><a href="#details" aria-controls="home"       role="tab" data-toggle="tab">Details</a></li>
            <li role="presentation"><a href="#registrant"             aria-controls="registrant" role="tab" data-toggle="tab">Registrant</a></li>
            <li role="presentation"><a href="#registrar"              aria-controls="registrar"  role="tab" data-toggle="tab">Registrar</a></li>
            <li role="presentation"><a href="#history"                aria-controls="history"    role="tab" data-toggle="tab">History</a></li>
        </ul>
        
        <!-- Tab panes -->
        <div class="tab-content">

            <!-- Details tab -->
            <div role="tabpanel" class="tab-pane active" id="details">
                <div class="row">
                    <div class="col-lg-6">
                        <table class="table table-condensed table-bordered">
                            <tbody>
                                <tr>
                                    <th style="width: 35%;">Domain Name</th>
                                    <td><?php echo $this->domain->getName(); ?></td>
                                </tr>
                                <tr>
                                    <th>Description</th>
                                    <td></td>
                                </tr>
                                <tr>
                                    <th>Name Servers</th>
                                    <td></td>
                                </tr>
                                <tr>
                                    <th>Status</th>
                                    <td>
                                        <?php foreach($this->domain->getStatuses() as $status):?>
                                        <?php echo $status->getStatus();?>
                                        <?php endforeach;?>
                                    </td>
                                </tr>
                                <tr>
                                    <th>Created</th>
                                    <td>
                                        <?php if ($this->domain->getCreated()) {
                                            echo $this->domain->getCreated()->format('d/m/Y');
                                        } ?>
                                    </td>
                                </tr>
                                <tr>
                                    <th>Changed</th>
                                    <td>
                                        <?php if ($this->domain->getChanged()) {
                                            echo $this->domain->getChanged()->format('d/m/Y');
                                        } ?>
                                    </td>
                                </tr>
                                <tr>
                                    <th>Expires</th>
                                    <td>
                                        <?php if ($this->domain->getExpires()) {
                                            echo $this->domain->getExpires()->format('d/m/Y');
                                        } ?>
                                    </td>
                                </tr>
                                
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>

            <!-- Registrar tab -->
            <div role="tabpanel" class="tab-pane" id="registrar">
                <div class="row">
                    <div class="col-lg-6">
                        <table class="table table-condensed table-bordered">
                            <tbody>
                                <tr>
                                    <th>Registrar</th>
                                    <td><?php echo $this->domain->getRegistrar(); ?></td>                        
                                </tr>
                                <tr>
                                    <th>Registrar URL</th>
                                    <td><a href="<?php echo $this->domain->getRegistrarUrl(); ?>"><?php echo $this->domain->getRegistrarUrl(); ?></a></td>                        
                                </tr>    
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            
            <!-- Registrant tab -->
            <div role="tabpanel" class="tab-pane" id="registrant">
                <div class="row">
                    <div class="col-lg-6">
                        <table class="table table-condensed table-bordered">
                            <tbody>
                                <tr>
                                    <th>Organisation</th>
                                    <td><?php echo $this->domain->getRegistrant(); ?></td>                        
                                </tr>
                                <tr>
                                    <th>Address</th>
                                    <td><?php echo $this->domain->getRegistrantAddress(); ?></td>                        
                                </tr>
                                <tr>
                                    <th>Type</th>
                                    <td><?php echo $this->domain->getRegistrantType(); ?></td>                        
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <!-- History tab -->
            <div role="tabpanel" class="tab-pane" id="history">
                <table class="table table-condensed table-bordered">
                    <thead>
                        <tr>
                            <th>Date & Time</th>
                            <th>Event</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->history as $history): ?>
                        <tr>
                            <td><?php echo $history->getTime()->format('d/m/Y h:i:s');?></td>
                            <td><?php echo $history->getEvent(); ?></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>