    <div class="row">
        <div class="col-md-12 title">
            <h1>Edit domain</h1>
            <hr>
        </div>
        <div class="col-md-6">
            <?php
                $form = $this->form;
                $form->setAttribute('action', $this->url('cobalt/default', array(
                    'controller' => 'domain',
                    'action'     => 'edit',
                    'id'         => $this->id)));
                $form->get('submit')->setOption('label', 'Edit');
                $form->prepare();
                echo $this->form()->openTag($form);
                echo $this->form($form);
                echo $this->form()->closeTag();
            ?>
        </div>
    </div>