<?php
    $this->headLink()->appendStylesheet('/css/dataTables.bootstrap.css');
    $this->headScript()->appendFile('/js/jquery.dataTables.js')
                       ->appendFile('/js/dataTables.bootstrap.js')
                       ->appendFile('/js/cobalt/domain/index.js');
?>

    <div class="row">
        <div class="col col-md-12 title">
            
            <h1>Domains</h1>
            <a class="btn btn-success pull-right" href="<?php echo $this->url('cobalt/default', array('controller' => 'domain', 'action' => 'add'));?>">Add Domain</a>
            <hr>
        </div>
        <div class="col-md-12">
            <table id="domains" class="table table-bordered table-cobalt">
                <thead>
                    <tr>
                        <th></th>
                        <th>Domain Name</th>
                        <th>Registrar</th>
                        <th>Status</th>
                        <th>Expires</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->domains as $domain): ?> 
                    <tr>
                        <td style="width: 1%;" nowrap>
                            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'domain', 'action' => 'refresh', 'id' => $domain->getId()));?>"><i class="fa fa-refresh"></i></a>
                            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'domain', 'action' => 'edit', 'id' => $domain->getId()));?>"><i class="fa fa-edit"></i></a>
                            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'domain', 'action' => 'delete', 'id' => $domain->getId()));?>"><i class="fa fa-remove"></i></a>
                        </td>
                        <td><a href="<?php echo $this->url('cobalt/default', array('controller' => 'domain', 'action' => 'detail', 'id' => $domain->getId()));?>">
                            <?php echo $domain->getName();?></a></td>
                        <td><?php echo $domain->getRegistrar();?></td>
                        <td></td>
                        <td>
                            <?php if ($domain->getExpires()) {
                                    echo $domain->getExpires()->format('d/m/Y');
                            }?>
                        </td>
                        
                    </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>

