<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Cobalt')?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:400,300,700')
                        ->prependStylesheet('https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css')
                        ->appendStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css')
                        ->appendStylesheet($this->basePath('css/style-v1.css'))
                        ->appendStylesheet('/css/form.css')
                        ->appendStylesheet('/css/style-v2.css');?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js')
                                      ->prependFile('/js/jquery-1.11.3.min.js') ?>

    </head>
    <body>
        
        <div class="l-header l-row">
            <img class="logo" src="/img/cobalt-logo.png">
            <span class="title">Cobalt Application</span>
            <span class="identity"><?php echo $this->profileMenu();?></span>
        </div>
            
        <div class="l-body l-row">
            
            <!-- Side navigation -->
            <div class="l-nav l-col l-scroll-y">
                <?php echo $this->navigation('navigation')->menu()
                                                          ->setMinDepth(0)
                                                          ->setMaxDepth(0)
                                                          ->setUlClass('side-nav')
                                                          ->escapeLabels(false);
                ?>  
            </div>
            
            <!-- content -->
            <div class="l-content l-col">
                
                <div class="l-row">
                    <div class="breadcrumb">
                        <?php echo $this->navigation('navigation')->breadcrumbs()
                                                                  ->setMinDepth(0)
                                                                  ->setPartial('cobalt/partial/breadcrumbs')?>
                    </div>
                </div>
                <div class="l-row l-pane l-scroll-y">
                    <div class="container-fluid">
                        <?php echo $this->content; ?>
                    </div>
                </div>
                
            </div>
        
        </div>
        
        <!-- footer -->
        <div class="l-footer l-row">
            <span class="pull-right">by S Rayner</span>
        </div>
        
        <?php echo $this->inlineScript() ?>
    </body>
</html>
