<table class="table table-condensed table-bordered">
    <thead>
        <tr>
            <th>Date & Time</th>
            <th>Event</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($this->history as $history): ?>
        <tr>
            <td style="width: 1%; white-space:nowrap;"><?php echo $history->getTime()->format('d/m/Y H:i:s');?></td>
            <td><?php echo $history->getEvent(); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>