        <ul class="nav navbar-nav pull-right">
            <li><button class="btn btn-default">
                    <i class="fa fa-bell"></i>
                    <span class="badge"></span>
                </button>
            <li>
            <li class="dropdown">
                <button class="btn btn-default dropdown-toggle" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    <i class="fa fa-plus"></i>
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu">
                    <li><a href="#">New Support Ticket</a></li>
                    <li><a href="#">New Task</a></li>
                    <li><a href="#">New Project</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">New User</a></li>
                    <li><a href="#">New Hardware</a></li>
                    <li><a href="#">New Software</a></li>
                </ul>
            </li>
            <li class="dropdown">
                <button class="btn btn-default dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    <i class="fa fa-user"></i> <?php echo $this->displayName; ?>
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu">
                    <li><a href="<?php echo $this->url('profile'); ?>"><i class="fa fa-fw fa-user"></i> My Profile</a></li>
                    <li><a href="<?php echo $this->url('settings'); ?>"><i class="fa fa-fw fa-edit"></i> Settings</a></li>
                    <li><a href="<?php echo $this->url('help'); ?>"><i class="fa fa-fw fa-life-ring"></i> Help</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="<?php echo $this->url('changepassword'); ?>"><i class="fa fa-fw fa-key"></i> Change Password</a></li>
                    <li><a href="<?php echo $this->url('logout'); ?>"><i class="fa fa-fw fa-sign-out"></i> Logout</a></li>
                </ul>
            </li>
        </ul>