<div class="row">
    <div class="col-md-12 title">
        <h1>Delete Question</h1>
        <hr>
        <p>Are you sure you want to delete the question '<i><?php echo $this->question->getQuestion(); ?>'</i> ?</p>
        
        <form action="<?php echo $this->url('faq/default', array(
            'controller' => 'index',
            'action' => 'delete',
            'id' => $this->question->getId()
        )); ?>" method="post">
            <div>
                <input class="btn btn-primary" type="submit" name="del" value="Yes" />
                <input class="btn btn-default" type="submit" name="del" value="No" />
            </div>
        </form>
    </div>
</div>