<div class="row">
    <div class="col-md-12 title">
        <h1>Frequently Asked Questions</h1>
        <a class="btn btn-success pull-right" href="<?php echo $this->url('faq/default', array('controller' => 'index', 'action' => 'add'));?>">New Question</a>
        <hr>
    </div>
    <div class="col-md-12">
        <?php foreach ($this->questions as $question): ?>
        <h4><?php echo $question->getQuestion(); ?></h4>
        <p><?php echo nl2br($question->getAnswer()); ?></p>
        <?php endforeach; ?>
    </div>
</div>