<div class="row">
    <div class="col-md-12 title">
        <h1>Frequently Asked Questions</h1>
        <a class="btn btn-success btn-sm pull-right" href="<?php echo $this->url('faq/default', array('controller' => 'index', 'action' => 'add'));?>">
            <i class="fa fa-question"></i> New Question</a>
        <hr>
    </div>
    <div class="col-md-12">
        <?php foreach ($this->questions as $question): ?>
        <h4><?php echo $question->getQuestion(); ?></h4>
        <table>
            <tr>
                <td valign="top">
                    <a href="<?php echo $this->url('faq/default', array('controller' => 'index', 'action' => 'edit', 'id' => $question->getId())); ?>"><i class="fa fa-edit"></i></a>
                    <a href="<?php echo $this->url('faq/default', array('controller' => 'index', 'action' => 'delete', 'id' => $question->getId())); ?>"><i class="fa fa-remove"></i></a>
                </td>
                <td>
                    <p><?php echo nl2br($question->getAnswer()); ?></p>
                </td>
            </tr>
        </table>
        <?php endforeach; ?>
       
    </div>
</div>