<?php
    $this->headLink()->appendStylesheet('/css/dataTables.bootstrap.css');
    $this->headScript()->appendFile('/js/jquery.dataTables.js')
                       ->appendFile('/js/dataTables.bootstrap.js')
                       ->appendFile('/js/cobalt/softwarecategory/index.js');
?>
        
    <div class="row">
        <div class="col col-md-12 title">
            <h1>Hardware Statuses</h1>
            <a class="btn btn-sm btn-success pull-right" href="<?php echo $this->url('cobalt/default', array('controller' => 'hardware-status', 'action' => 'add'));?>">New Status</a>
            <hr>
        </div>
        <div class="col-md-12">
            <table id="computers" class="table table-bordered table-cobalt" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th></th>
                        <th>Name</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->statuses as $status): ?> 
                    <tr>
                        <td style="width: 1%;" nowrap>
                            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'hardware-status', 'action' => 'edit', 'id' => $status->getId()));?>"><i class="fa fa-edit"></i></a>
                            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'hardware-status', 'action' => 'delete', 'id' => $status->getId()));?>"><i class="fa fa-remove"></i></a>
                        </td>
                        <td><a href="<?php echo $this->url('cobalt/default', array('controller' => 'hardware-status', 'action' => 'detail', 'id' => $status->getId()));?>">
                            <?php echo $status->getName();?></a></td>
                        <td><?php echo nl2br($status->getDescription());?></td>
                    </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>