<div class="row">
        <div class="col-md-12">
        
            <h1>New comment</h1>
            <hr>
    
            <?php
                $form = $this->form;
                $form->setAttribute('action', $this->url('project/default', array(
                    'controller' => 'comment',
                    'action' => 'add',
                    'id' => $this->id
                )));
                $form->prepare();

                echo $this->form($form);
            ?>
       
        </div> 
    </div>