<div class="row">
        <div class="col-md-12 title">
        
            <h1>Edit comment</h1>
            <hr>
        </div>
        <div class="col-md-12">
            <?php
                $form = $this->form;
                $form->get('submit')->setOption('label', 'Edit');
                $form->setAttribute('action', $this->url('project/default', array(
                    'controller' => 'comment',
                    'action' => 'edit',
                    'id' => $this->id
                )));
                $form->prepare();

                echo $this->form($form);
            ?>
       
        </div> 
    </div>