    
    <div class="row">
        <div class="col-md-12 title">
            <h1>Add new user</h1>
            <hr>
        </div>
        <div class="col-md-6">

            <?php
                $form = $this->form;
                $form->setAttribute('action', $this->url('cobalt/default', array('controller' => 'user', 'action' => 'add', 'id' => $this->userId)));
                $form->prepare();

                echo $this->form($form);
            ?>
        </div>
    </div>
