    
    <!-- Breadcrumb -->
    <ul class="breadcrumb">
        <li><a href="<?php echo $this->url('cobalt');?>"><i class="fa fa-home"></i> Home</a></li>
        <li><a href="<?php echo $this->url('cobalt/default', array('controller' => 'enduser', 'action' => 'index'));?>"><i class="fa fa-angle-right"></i> Users</a></li>
        <li><i class="fa fa-angle-right"></i> Add new users</li>
    </ul>

    <div class="row">
        <div class="col-12">
            <h1>Add new user</h1>
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-6">

        <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('cobalt/default', array('controller' => 'enduser', 'action' => 'add', 'id' => $this->userId)));
            $form->prepare();

            echo $this->form()->openTag($form);
            echo $this->formCollection($form);
            echo $this->form()->closeTag();
        ?>

        </div>
    </div>
