    <div class="row">
        <div class="col-md-12 title">
            <h1>Add Hardware to <?php echo $this->user->getDisplayName(); ?></h1>
            <hr>
        </div>
        
        <div class="col-md-6">
            <form class="form-horizontal" method="post">
                <div class="form-group">
                    <label for="hardware" class="col-sm-2 control-label">Hardware</label>
                    <div class="col-sm-10">
                        <select class="form-control" name="hardware">
                        <?php foreach ($this->hardware as $hardware): ?>
                            <option value="<?php echo $hardware->getId(); ?>"><?php echo $hardware->getName(); ?></option>
                        <?php endforeach; ?>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-primary">O.K.</button>
                    </div>
                </div>
            </form>
            
        </div>
        
    </div>