    <div class="row">
        <div class="col-md-12 title">
            <h1>Add Role to <?php echo $this->user->getDisplayName(); ?></h1>
            <hr>
        </div>
        
        <div class="col-md-6">
            <form class="form-horizontal" method="post">
                <div class="form-group">
                    <label for="role" class="col-sm-2 control-label">Role</label>
                    <div class="col-sm-10">
                        <select class="form-control" name="role">
                        <?php foreach ($this->roles as $role): ?>
                            <option><?php echo $role->getRole(); ?></option>
                        <?php endforeach; ?>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-primary">O.K.</button>
                    </div>
                </div>
            </form>
            
        </div>
        
    </div>
