<?php
$this->inlineScript()->appendFile('/js/draw.js', 'text/javascript')
                     ->appendFile('/js/cobalt/user/detail.js', 'text/javascript');

?>

<div class="row">
    <div class="col-md-12 title">
        <h1>User Details</h1>
        <hr>
        
        <i class="fa fa-user fa-3x pull-left"></i>
        <h4><?php echo $this->user->getDisplayName(); ?></h4>
        <p>
            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'user', 'action' => 'edit', 'id' => $this->user->getId())); ?>"><i class="fa fa-edit"></i></a>
            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'user', 'action' => 'delete', 'id' => $this->user->getId())); ?>"><i class="fa fa-remove"></i></a>
        </p>

    
        <div>
            <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist" id="tabs">
                <li role="presentation" class="active"><a href="#detail" aria-controls="home" role="tab" data-toggle="tab">Information</a></li>
                <li role="presentation"><a id="r" href="#account" aria-controls="account" role="tab" data-toggle="tab">Active Directory</a></li>
                <li role="presentation"><a id="r" href="#relationships" aria-controls="milestones" role="tab" data-toggle="tab">Relationships</a></li>
                <li role="presentation"><a href="#history" aria-controls="history" role="tab" data-toggle="tab">History</a></li>
            </ul>
        
            <!-- Tab panes -->
            <div class="tab-content">
                
                <!-- User info tab -->
                <div role="tabpanel" class="tab-pane active" id="detail">
                    <div class="row">
                        
                        <div class="col-lg-6">
                            <table class="table table-condensed table-bordered">
                                <tbody>
                                    <tr>
                                        <th style="width: 35%;">Account Name</th>
                                        <td><?php echo $this->user->getSamAccountName(); ?></td>
                                    </tr>
                                     <tr>
                                        <th style="width: 35%;">Display Name</th>
                                        <td><?php echo $this->user->getDisplayName(); ?></td>
                                    </tr>
                                    <tr>
                                        <th>Description</th>
                                        <td><?php echo $this->user->getDescription(); ?></td>
                                    </tr>
                                    <tr>
                                        <th>User Principle Name</th>
                                        <td><?php echo $this->user->getUserPrincipalName(); ?></td>
                                    </tr>
                                    <tr>
                                        <th>Email</th>
                                        <td><a href="mailto:<?php echo $this->user->getEmail(); ?>"><?php echo $this->user->getEmail(); ?></a></td>
                                    </tr>
                                    <tr>
                                        <th>Telephone No</th>
                                        <td><?php echo $this->user->getTelephoneNumber(); ?></td>
                                    </tr>
                                     <tr>
                                        <th>Extension No</th>
                                        <td><?php echo $this->user->getExtensionNumber(); ?></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        
                        <div class="col-lg-6">
                            <table class="table table-condensed table-bordered">
                                <tbody>
                                    <tr>
                                        <th style="width: 35%;">Company</th>
                                        <td><?php echo $this->user->getCompany(); ?></td>
                                    </tr>
                                     <tr>
                                        <th style="width: 35%;">Office</th>
                                        <td><?php echo $this->user->getOffice(); ?></td>
                                    </tr>
                                    <tr>
                                        <th>Department</th>
                                        <td><?php echo $this->user->getDepartment(); ?></td>
                                    </tr>
                                    <tr>
                                        <th>Job Title</th>
                                        <td><?php echo $this->user->getTitle(); ?></td>
                                    </tr>
                                    <tr>
                                        <th>Mobile Number</th>
                                        <td><?php echo $this->user->getMobileNumber(); ?></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        
                        
                    </div>
                </div>
                
                <!-- Account tab -->
                <div role="tabpanel" class="tab-pane" id="account">
                    <div class="row">
                        
                        <div class="col-lg-6">
                            <table class="table table-condensed table-bordered">
                                <tbody>
                                    <tr>
                                        <th style="width: 35%;">Bad Password Count</th>
                                        <td><?php echo $this->user->getBadPasswordCount(); ?></td>
                                    </tr>
                                     <tr>
                                        <th style="width: 35%;">Bad Password Time</th>
                                        <td><?php echo date_format($this->user->getBadPasswordTime(), 'd/m/Y H:i:s'); ?></td>
                                    </tr>
                                    
                                </tbody>
                            </table>
                        </div>
               
                    </div>
                </div>
                
                <!-- Relationships tab -->
                <div role="tabpanel" class="tab-pane" id="relationships">
                     <div id="canvas-container" style="height: 400px; width: 100%; overflow:hidden">
                         
                         <canvas id="myCanvas" width="800" height="400"></canvas>  
                    </div>
                </div>
                
 
                
                <!-- History tab -->
                <div role="tabpanel" class="tab-pane" id="history">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Date & Time</th>
                                <th>Event</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($this->history as $history): ?>
                            <tr>
                                <td><?php echo $history->getTime()->format('d/m/Y h:i:s');?></td>
                                <td><?php echo $history->getEvent(); ?></td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
        
        
    </div>
</div>
<br>
    