<?php
$this->inlineScript()->appendFile('/js/bootstrap/tab.js')
                     ->appendFile('/js/jquery-plugin/stickytabs.js')
                     ->appendFile('/js/draw.js', 'text/javascript')
                     ->appendFile('/js/cobalt/user/detail.js', 'text/javascript');

?>

<div class="row">
    <div class="col-md-12 title">
        <h1>User Details</h1>
        <hr>
        
        <i class="fa fa-user fa-3x pull-left"></i>
        <h4><?php echo $this->user->getDisplayName(); ?></h4>
        <p>
            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'user', 'action' => 'edit', 'id' => $this->user->getId())); ?>"><i class="fa fa-edit"></i></a>
            <a href="<?php echo $this->url('cobalt/default', array('controller' => 'user', 'action' => 'delete', 'id' => $this->user->getId())); ?>"><i class="fa fa-remove"></i></a>
        </p>

    
        <div>
            <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist" id="tabs">
                <li role="presentation" class="active"><a href="#detail" aria-controls="home" role="tab" data-toggle="tab">Information</a></li>
                <li role="presentation"><a href="#account" aria-controls="account" role="tab" data-toggle="tab">Active Directory</a></li>
                <li role="presentation" id="r"><a href="#relationships" aria-controls="milestones" role="tab" data-toggle="tab">Relationships</a></li>
                <li role="presentation"><a href="#hardware" aria-controls="roles" role="tab" data-toggle="tab">Hardware</a></li>
                <li role="presentation"><a href="#roles" aria-controls="roles" role="tab" data-toggle="tab">Roles</a></li>
                <li role="presentation"><a href="#history" aria-controls="history" role="tab" data-toggle="tab">History</a></li>
            </ul>
        
            <!-- Tab panes -->
            <div class="tab-content">
                
                <!-- User info tab -->
                <div role="tabpanel" class="tab-pane active" id="detail">
                    <div class="row">
                        
                        <div class="col-lg-6">
                            <table class="table table-condensed table-bordered">
                                <tbody>
                                    <tr>
                                        <th style="width: 35%;">Account Name</th>
                                        <td><?php echo $this->user->getSamAccountName(); ?></td>
                                    </tr>
                                     <tr>
                                        <th style="width: 35%;">Display Name</th>
                                        <td><?php echo $this->user->getDisplayName(); ?></td>
                                    </tr>
                                    <tr>
                                        <th>Description</th>
                                        <td><?php echo $this->user->getDescription(); ?></td>
                                    </tr>
                                    <tr>
                                        <th>User Principle Name</th>
                                        <td><?php echo $this->user->getUserPrincipalName(); ?></td>
                                    </tr>
                                    <tr>
                                        <th>Email</th>
                                        <td><a href="mailto:<?php echo $this->user->getEmailAddress(); ?>"><?php echo $this->user->getEmailAddress(); ?></a></td>
                                    </tr>
                                    <tr>
                                        <th>Telephone No</th>
                                        <td><?php echo $this->user->getTelephoneNumber(); ?></td>
                                    </tr>
                                     <tr>
                                        <th>Extension No</th>
                                        <td><?php echo $this->user->getExtensionNumber(); ?></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        
                        <div class="col-lg-6">
                            <table class="table table-condensed table-bordered">
                                <tbody>
                                    <tr>
                                        <th style="width: 35%;">Company</th>
                                        <td><?php echo ($this->user->getCompany() ? $this->user->getCompany()->getName() : ''); ?></td>
                                    </tr>
                                     <tr>
                                        <th style="width: 35%;">Office</th>
                                        <td><?php echo ($user->getOffice()? $user->getOffice()->getName() : ''); ?></td>
                                    </tr>
                                    <tr>
                                        <th>Department</th>
                                        <td><?php echo $this->user->getDepartment(); ?></td>
                                    </tr>
                                    <tr>
                                        <th>Job Title</th>
                                        <td><?php echo $this->user->getTitle(); ?></td>
                                    </tr>
                                    <tr>
                                        <th>Reports To</th>
                                        <td>
                                            <?php if ($user->getReportsTo()):?>
                                            <a href ="<?php echo $this->url('cobalt/default', array(
                                                'controller' => 'user',
                                                'action' => 'detail',
                                                'id' => $user->getReportsTo()->getId()
                                            ))?>"><?php echo ($user->getReportsTo()->getDisplayName());?></a>
                                            <?php endif; ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>Mobile Number</th>
                                        <td><?php echo $this->user->getMobileNumber(); ?></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        
                        
                    </div>
                </div>
                
                <!-- Account tab -->
                <div role="tabpanel" class="tab-pane" id="account">
                    <div class="row">
                        
                        <div class="col-lg-6">
                            <table class="table table-condensed table-bordered">
                                <tbody>
                                    <tr>
                                        <th style="width: 35%;">Bad Password Count</th>
                                        <td><?php echo $this->user->getBadPasswordCount(); ?></td>
                                    </tr>
                                     <tr>
                                        <th style="width: 35%;">Bad Password Time</th>
                                        <td><?php echo !$this->user->getBadPasswordTime() ? '' : date_format($this->user->getBadPasswordTime(), 'd/m/Y H:i:s'); ?></td>
                                    </tr>
                                    
                                </tbody>
                            </table>
                        </div>
               
                    </div>
                </div>
                
                <!-- Relationships tab -->
                <div role="tabpanel" class="tab-pane" id="relationships">
                     <div id="canvas-container" style="height: 400px; width: 100%; overflow:hidden">
                         
                         <canvas id="myCanvas" width="800" height="400"></canvas>  
                    </div>
                </div>
                
                <!-- Hardware tab -->
                <div role="tabpanel" class="tab-pane" id="hardware">
                    <div class="row">
                        <div class="col-md-12">
                            <table class="table table-condensed table-bordered">
                                <tr>
                                    <th></th>
                                    <th>Hardware Name</th>
                                    <th>Type</th>
                                </tr>
                                <?php foreach($user->getHardware() as $hardware): ?>
                                <tr>
                                    <td style="width: 1%; padding-right: 10px;" nowrap>
                                        <a href="<?php echo $this->url('cobalt/default', array(
                                            'controller' => 'user',
                                            'action' => 'removehardware',
                                            'id' => $user->getId() . '_' . $hardware->getId()));?>">
                                            <i class="fa fa-remove"></i>
                                        </a>
                                    </td>
                                    <td><a href="<?php echo $this->url('cobalt/default', array(
                                        'controller' => 'hardware',
                                        'action'     => 'detail',
                                        'id'         => $hardware->getId()
                                    ))?>"><?php echo $hardware->getName(); ?></a></td>
                                    <td><?php echo $hardware->getType()->getName(); ?></td>
                                </tr>
                                <?php endforeach; ?>
                                
                            </table>
                            <a class="btn btn-default btn-sm" href="<?php echo $this->url('cobalt/default', array(
                            'controller' => 'user',
                            'action' => 'addhardware',
                            'id' => $user->getId()
                        )) ?>">Add Hardware</a>
                        </div>
                    </div>                     
                </div>
                
                <!-- Roles tab -->
                <div role="tabpanel" class="tab-pane" id="roles">
                    <div class="row">
                        <div class="col-md-12">
                            <table class="table table-condensed table-bordered">
                                <tr>
                                    <th></th>
                                    <th>Role</th>
                                    <th>Type</th>
                                </tr>
                                <?php foreach($user->getRoles() as $role): ?>
                                <tr>
                                    <td style="width: 1%;" nowrap>
                                        <?php if ($role->getName() != 'user'): ?>
                                        <a href="<?php echo $this->url('cobalt/default', array(
                                            'controller' => 'user',
                                            'action' => 'removerole',
                                            'id' => $role->getId()));?>">
                                            <i class="fa fa-remove"></i>
                                        </a>
                                        <?php endif; ?>
                                    </td>
                                    <td><?php echo $role->getName(); ?></td>
                                    <td><?php echo $role->getType(); ?></td>
                                </tr>
                                <?php endforeach; ?>
                                
                            </table>
                            <a class="btn btn-default btn-sm" href="<?php echo $this->url('cobalt/default', array(
                            'controller' => 'user',
                            'action' => 'addrole',
                            'id' => $user->getId()
                        )) ?>">Add Role</a>
                        </div>
                    </div>                     
                </div>
                
                <!-- History tab -->
                <div role="tabpanel" class="tab-pane" id="history">
                    <?php echo $this->partial('application/partial/history_table.phtml', array('history' => $this->history));?>
                </div>
                
            </div>

        </div>
            
    </div>
</div>
<br>
    