<?php
    $this->inlineScript()->appendFile('/js/cobalt/user/edit.js');
?>
    
<div class="row">
    <div class="col-md-12 title">
        <h1>Edit user</h1>
        <hr>
    </div>
    <div class="col-md-6">
        <?php
            $form = $this->form;
            $form->get('submit')->setOption('label', 'Edit');
            $form->setAttribute('action', $this->url('cobalt/default', array('controller' => 'user', 'action' => 'edit', 'id' => $this->id)));
            $form->prepare();
            echo $this->form($form);
        ?>
    </div>
</div>
