<?php

  $node = new StdClass();
  $node->id = 'u' . $this->user->getId();
  $node->name = $this->user->getDisplayName();#
  $node->type = 'user';
  
  $manager = new StdClass();
  $manager->id = 'u' . $this->reportsTo->getId();
  $manager->name = $this->reportsTo->getDisplayName();#
  $manager->type = 'user';
  
  $nodes = new StdClass();
  $nodes->nodes = array($node, $manager);
  
  $r1 = new StdClass();
  $r1->id = 'r1';
  $r1->from = $node->id;
  $r1->to = $node->id;
  $r1->label = 'Is the same as';
  
  $r2 = new StdClass();
  $r2->id = 'r2';
  $r2->from = $node->id;
  $r2->to = $manager->id;
  $r2->label = 'Reports To';
  
  $relationships = new stdClass();
  $relationships->relationships = array($r1, $r2);
  
  $result = json_encode(array($nodes, $relationships));
  
  echo $result;
  die;   
?>

