<?php

  // User node.
  $userNode = new StdClass();
  $userNode->id = 'u' . $this->user->getId();
  $userNode->name = $this->user->getDisplayName();
  $userNode->type = 'user';
  
  // Manager node.
  $managerNode = new StdClass();
  $managerNode->id = 'u' . $this->reportsTo->getId();
  $managerNode->name = $this->reportsTo->getDisplayName();
  $managerNode->type = 'user';
  
  $nodes = new StdClass();
  $nodes->nodes = array($userNode, $managerNode);
  
  // User/manager relationship.
  $r2 = new StdClass();
  $r2->id = 'r2';
  $r2->from = $userNode->id;
  $r2->to = $managerNode->id;
  $r2->label = 'Reports To';
  
  $relationships = new stdClass();
  $relationships->relationships = array($r2);
  
  $i = 3;
  foreach($this->user->getHardware() as $hardware)
  {
      $n = new StdClass();
      $n->id = 'c' . $hardware->getId();
      $n->name = $hardware->getName();
      $n->type = 'computer';
      array_push($nodes->nodes, $n);
      
      $r = new StdClass();
      $r->id = 'r' . $i;
      $r->from = $userNode->id;
      $r->to = $n->id;
      $r->label = 'Uses';
      array_push($relationships->relationships, $r);
      
      $i++;
  }
  
  
  
  $result = json_encode(array($nodes, $relationships));
  
  echo $result;
  die;   
?>

