<div class="row">
    <div class="col-md-12 title">
        <h1>Remove Role</h1>
        <hr>
        <p>Are you sure you want to remove the role <?php echo $this->role->getParent(); ?>?</p>
        
        <form action="<?php echo $this->url('cobalt/default', array(
            'controller' => 'user',
            'action' => 'removerole',
            'id' => $this->role->getRoleId()
        )); ?>" method="post">
            <div>
                <input class="btn btn-primary" type="submit" name="del" value="Yes" />
                <input class="btn btn-default" type="submit" name="del" value="No" />
            </div>
        </form>
    </div>
</div>