<?php $this->headScript()->appendFile('/js/jquery.are-you-sure.js')
                         ->appendFile('/js/project/milestone/add.js'); ?>

    <div class="row">
        <div class="col-md-12 title">
        
            <h1>New milestone</h1>
            <hr>
    
            <?php
                $form = $this->form;
                $form->setAttribute('action', $this->url('project/default', array(
                    'controller' => 'milestone',
                    'action' => 'add',
                    'id' => $this->projectId
                )));
                $form->prepare();

                echo $this->form($form);
            ?>
       
        </div> 
    </div>