    <div class="row">
        <div class="col-md-12">
        
            <h1>New milestone</h1>
            <hr>
    
            <?php
                $form = $this->form;
                $form->setAttribute('action', $this->url('project/default', array('controller' => 'milestone', 'action' => 'add')));
                $form->prepare();

                echo $this->form($form);
            ?>
       
        </div> 
    </div>