<?php
    $this->headScript()->appendFile('/js/bootstrap/tab.js')
                       ->appendFile('/js/jquery-plugin/stickytabs.js')
                       ->appendFile('/js/project/milestone/detail.js');
?>

<div class="row">
    
    <!-- Page title -->
    <div class="col-md-12 title">
        <h1>Milestone Details</h1>
        <hr>
    </div>
    
     <!-- Milestone header -->
    <div class="col-lg-6">
        <i class="fa fa-cubes fa-3x pull-left"></i>
        <h4 style="margin-top: 0;"><?php echo $this->milestone->getName(); ?></h4>
        <p>
            <a href="<?php echo $this->url('project/default', array('controller' => 'milestone', 'action' => 'edit', 'id' => $this->milestone->getId())); ?>"><i class="fa fa-edit"></i></a>
            <a href="<?php echo $this->url('project/default', array('controller' => 'milestone', 'action' => 'delete', 'id' => $this->milestone->getId())); ?>"><i class="fa fa-remove"></i></a>
        </p>
    </div>
    
    <!-- Project progress -->
    <div class="col-lg-6">
        <div class="pull-right">
            <div class="proj-progress">
                <div class="proj-progress-header">
                    <span>Tasks</span>
                </div>
                <div class="proj-progress-body">
                    <div class="proj-progress-left">
                        <span><?php echo $this->milestone->getTaskCount(); ?></span>   
                    </div>
                    <div class="proj-progress-right proj-progress-blue">
                        <span><?php echo $this->milestone->getTaskCompleted(); ?></span>
                        <i class="fa fa-check"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <!-- Milestone description -->
    <div class="col-lg-12">
        <p><?php echo $this->milestone->getDescription();?></p>
        
        <div>
            <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist" id="tabs">
                <li role="presentation" class="active"><a href="#detail" aria-controls="home" role="tab" data-toggle="tab">Detail</a></li>
                <li role="presentation"><a href="#tasks" aria-controls="tasks" role="tab" data-toggle="tab">Tasks</a></li>
                <li role="presentation"><a href="#history" aria-controls="history" role="tab" data-toggle="tab">History</a></li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content">
                
                <!-- Project details tab -->
                <div role="tabpanel" class="tab-pane active" id="detail">
                    <div class="row">
                        
                        <div class="col-lg-6">
                            <table class="table table-condensed table-bordered">
                                <tbody>
                                     <tr>
                                        <th style="width: 35%;">Name</th>
                                        <td><?php echo $this->milestone->getName(); ?></td>
                                    </tr>
                                    <tr>
                                        <th>Project</th>
                                        <td><a href="<?php echo $this->url('project/default', array(
                                            'controller' => 'project',
                                            'action'     => 'detail',
                                            'id'         => $this->milestone->getProject()->getId()
                                                ));?>"><?php echo $this->milestone->getProject()->getName();?></a></td>
                                    </tr>
                                    <tr>
                                        <th>Scheduled Start Date</th>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <th>Estimated Hours</th>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <th>Estimated Cost</th>
                                        <td></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        
                        <div class="col-lg-6">
                            <table class="table table-condensed table-bordered">
                                <tbody>
                                    <tr>
                                        <th style="width: 35%;">Status</th>
                                        <td><div class="status status-<?php echo $this->milestone->getStatus()->getColour();?>">
                                            <?php echo $this->milestone->getStatus()->getName(); ?>
                                        </div></td>
                                    </tr>
                                    <tr>
                                        <th>Owner</th>
                                        <td>Fred Bloggs</td>
                                    </tr>
                                    <tr>
                                        <th>Priority</th>
                                        <td><div class="status status-<?php echo $this->milestone->getPriority()->getColour();?>">
                                            <?php echo $this->milestone->getPriority()->getName(); ?>
                                        </div></td>
                                    </tr>
                                    <tr>
                                        <th>Actual Hours</th>
                                        <td>2</td>
                                    </tr>
                                    <tr>
                                        <th>Actual Cost</th>
                                        <td>50</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        
                    </div>
                </div>
                
                <!-- Tasks tab -->
                <div role="tabpanel" class="tab-pane" id="tasks">
                    <div class="row">
                        <div class="col-md-12">
                            <table class="table table-condensed">
                                <tr>
                                    <th></th>
                                    <th>Name</th>
                                    <th>Description</th>
                                    <th>Status</th>
                                    <th>Priority</th>
                                    
                                </tr>
                                <?php foreach ($this->milestone->getTasks() as $task): ?>
                                <tr>
                                    <td style="width: 1%;" nowrap>
                                        <a href="<?php echo $this->url('project/default', array('controller' => 'task', 'action' => 'edit', 'id' => $task->getId()));?>">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                        <a href="<?php echo $this->url('project/default', array('controller' => 'task', 'action' => 'delete', 'id' => $task->getId()));?>">
                                            <i class="fa fa-remove"></i>
                                        </a>
                                    </td>
                                    <td><a href="<?php echo $this->url('project/default', array('controller' => 'task', 'action' => 'detail', 'id' => $task->getId()));?>">
                                        <?php echo $task->getName(); ?>
                                    </a></td>
                                    <td><?php echo $task->getDescription(); ?></td>
                                    <td><?php echo $task->getStatus()->getName(); ?></td>
                                    <td><?php echo $task->getPriority()->getName(); ?></td>
                                </tr>
                                <?php endforeach; ?>
                            </table>
                        </div>
                    </div>
                    <a class="btn btn-default btn-sm" href="<?php echo $this->url('project/default', array(
                                'controller' => 'task',
                                'action' => 'add',
                                'id' => $this->milestone->getId()
                            )) ?>">Add Task</a>
                </div>
                
                <!-- History tab -->
                <div role="tabpanel" class="tab-pane" id="history">
                    History
                </div>
            </div>

        </div>
        <br>
        
        <p>
        <span class="text-primary">Comments</span>
        <a class="btn btn-primary btn-xs pull-right" href="<?php echo $this->url('project/default', array(
            'controller' => 'milestone',
            'action' => 'comment',
            'id' => $this->milestone->getId()
        )) ?>">Add Comment</a>
        </p>
        <?php foreach($this->milestone->getComments() as $comment):?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <b>Guest </b><small class="text-muted"><?php echo $comment->getCreatedTime()->format(DATE_COOKIE); ?></small>
                <span class="pull-right">
                    <a href="<?php echo $this->url('project/default', array('controller' => 'comment', 'action' => 'edit', 'id' => $comment->getId())); ?>"><i class="fa fa-edit"></i></a>
                    <a href="<?php echo $this->url('project/default', array('controller' => 'comment', 'action' => 'delete', 'id' => $comment->getId())); ?>"><i class="fa fa-remove"></i></a>
                </span>
            </div>
            <div class="panel-body">
                <p><?php echo $comment->getComment();?></p>
            </div>        
        </div>
        <?php endforeach;?>
        
    </div>
</div>
