<?php $this->headScript()->appendFile('/js/jquery.are-you-sure.js')
                         ->appendFile('/js/project/milestone/edit.js'); ?>

<div class="row">
    
    <div class="col-md-12 title">
        <h1>Edit milestone</h1>
        <hr>
    </div>
    
    <div class="col-md-12">
        <?php
            $form = $this->form;
            $form->get('submit')->setOption('label', 'Edit');
            $form->setAttribute('action', $this->url('project/default', array('controller' => 'milestone', 'action' => 'edit', 'id' => $this->id)));
            $form->prepare();

            echo $this->form($form);
        ?>
        
    </div>
</div>