    
    <div class="row">
        <div class="col-12">
            <h1 class="title">Milestones</h1>
            <a class="btn btn-action pull-right" href="<?php echo $this->url('project/default', array('controller' => 'milestone', 'action' => 'add'));?>">New Milestone</a>
            <hr>

            <table id="tasks" class="display" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Status</th>
                        <th>Priority</th>
                        <th>Actions</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>