<div class="row">
    <div class="col-md-12 title">   
        <h1>Help</h1>
        <hr>
    </div>
    <div class="col-md-12">
        
        <h4>Organisation</h5>
        <p>Structure you organisation by creating companies with offices and departments.
            Then you users can be assigned to an office and a department. Users can also
            report to other users, creating an organisational hierarchy.</p><br>
        
        <h4>Assets</h5>
        <p>Keep track of your hardware and software by assigning a status. The overviews
            can then show you how many of each item you have and what state it is in.
            By assign assets to users you can see who is using what.</p><br>
        
        <h4>Support Helpdesk</h5>
        <p>Create tickets to track user support requests. Assign a technician to the
            ticket so both the requestor and the technician know who is responsible for
            dealing with the request. The dashboard can show how many open tickets there
            are at any given time.</p><br>
        
        <h4>Projects</h4>
        <p>Organise your tasks into projects and milestones. Milestone can be added to projects
            in order to break them down into specific achievable goals. Tasks can be added to
            either a specific milestone, or to the project generally.</p><br>
            
        <h4>Domains</h4>
        <p>Add you domain names to get a quick overview of all your domains no matter
            which hosting company you are using. Quickly see the expiry dates, or drill
            into the detail for more info.</p><br>
        
        <h4>FAQ</h4>
        <p>Use the FAQ section to add questions and answer for common problems that occur
            in your environment. These can aid both technicians as well as normal users.</p>
    </div>
</div>
