    <div class="row">
        <div class="col-md-12 title">
            <h1>Outgoing Mail Server Configuration</h1>
            <hr>
        </div>
        <div class="col-md-6">
            <?php
                $form = $this->form;
                $form->setAttribute('action', $this->url('mailoutconfig'));
                $form->prepare();
                echo $this->form()->openTag($form);
                echo $this->form($form);
                echo $this->form()->closeTag();
            ?>
        </div>
    </div>